<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\AcademicCalendar;
use App\Models\AcademicProgram;

class AcademicCalendarSeeder extends Seeder
{
    public function run(): void
    {
        $programs = AcademicProgram::all();
        
        $events = [
            [
                'title_en' => 'Fall Semester 2026 Registration Opens',
                'title_km' => 'ការចុះឈ្មោះឆមាសរដូវកាល2026',
                'description_en' => 'Registration for Fall Semester 2026 opens for all students.',
                'description_km' => 'ការចុះឈ្មោះសម្រាប់ឆមាសរដូវកាល2026 បើកសម្រាប់និស្សិតទាំងអស់។',
                'event_type' => 'registration',
                'start_date' => '2026-03-01',
                'end_date' => '2026-03-15',
                'is_all_day' => true,
                'audience' => 'all',
                'color_code' => '#007bff',
                'is_active' => true,
                'sort_order' => 1,
            ],
            [
                'title_en' => 'New Student Orientation',
                'title_km' => 'ការណែនាំនិស្សិតថ្មី',
                'description_en' => 'Orientation program for new students joining the university.',
                'description_km' => 'កម្មវិធីណែនាំសម្រាប់និស្សិតថ្មីដែលចូលរៀននៅសាកលវិទ្យាល័យ។',
                'event_type' => 'orientation',
                'start_date' => '2026-08-15',
                'end_date' => '2026-08-17',
                'is_all_day' => true,
                'audience' => 'students',
                'color_code' => '#20c997',
                'is_active' => true,
                'sort_order' => 2,
            ],
            [
                'title_en' => 'Fall Semester 2026 Begins',
                'title_km' => 'ចាប់ផ្តើមឆមាសរដូវកាល2026',
                'description_en' => 'First day of classes for Fall Semester 2026.',
                'description_km' => 'ថ្ងៃដំបូងនៃការសិក្សាសម្រាប់ឆមាសរដូវកាល2026។',
                'event_type' => 'semester_start',
                'start_date' => '2026-09-01',
                'is_all_day' => true,
                'audience' => 'all',
                'color_code' => '#17a2b8',
                'is_active' => true,
                'sort_order' => 3,
            ],
            [
                'title_en' => 'Midterm Examination Period',
                'title_km' => 'រយៈពេលប្រឡងពាក់កណ្តាលឆមាស',
                'description_en' => 'Midterm examinations for all courses.',
                'description_km' => 'ការប្រឡងពាក់កណ្តាលឆមាសសម្រាប់មេរៀនទាំងអស់។',
                'event_type' => 'exam_period',
                'start_date' => '2026-10-15',
                'end_date' => '2026-10-22',
                'is_all_day' => true,
                'audience' => 'students',
                'color_code' => '#fd7e14',
                'is_active' => true,
                'sort_order' => 4,
            ],
            [
                'title_en' => 'Course Withdrawal Deadline',
                'title_km' => 'ថ្ងៃបិទការដកមេរៀន',
                'description_en' => 'Last day to withdraw from courses without penalty.',
                'description_km' => 'ថ្ងៃចុងក្រោយដកមេរៀនដោយគ្មានទោស។',
                'event_type' => 'academic_deadline',
                'start_date' => '2026-10-30',
                'is_all_day' => true,
                'audience' => 'students',
                'color_code' => '#dc3545',
                'is_active' => true,
                'sort_order' => 5,
            ],
            [
                'title_en' => 'National Independence Day',
                'title_km' => 'បុណ្យឯករាជ្យជាតិ',
                'description_en' => 'Public holiday - National Independence Day of Cambodia.',
                'description_km' => 'ថ្ងៃឈប់សាធារណៈ - បុណ្យឯករាជ្យជាតិកម្ពុជា។',
                'event_type' => 'holiday',
                'start_date' => '2026-11-09',
                'is_all_day' => true,
                'audience' => 'all',
                'color_code' => '#28a745',
                'is_active' => true,
                'sort_order' => 6,
            ],
            [
                'title_en' => 'Final Examination Period',
                'title_km' => 'រយៈពេលប្រឡងបញ្ចប់ឆមាស',
                'description_en' => 'Final examinations for all courses.',
                'description_km' => 'ការប្រឡងបញ្ចប់ឆមាសសម្រាប់មេរៀនទាំងអស់។',
                'event_type' => 'exam_period',
                'start_date' => '2026-12-01',
                'end_date' => '2026-12-15',
                'is_all_day' => true,
                'audience' => 'students',
                'color_code' => '#fd7e14',
                'is_active' => true,
                'sort_order' => 7,
            ],
            [
                'title_en' => 'Fall Semester 2026 Ends',
                'title_km' => 'បញ្ចប់ឆមាសរដូវកាល2026',
                'description_en' => 'Last day of classes for Fall Semester 2026.',
                'description_km' => 'ថ្ងៃចុងក្រោយនៃការសិក្សាសម្រាប់ឆមាសរដូវកាល2026។',
                'event_type' => 'semester_end',
                'start_date' => '2026-12-15',
                'is_all_day' => true,
                'audience' => 'all',
                'color_code' => '#6f42c1',
                'is_active' => true,
                'sort_order' => 8,
            ],
            [
                'title_en' => 'Grade Submission Deadline',
                'title_km' => 'ថ្ងៃបិទការដាក់ពិន្ទុ',
                'description_en' => 'Faculty must submit final grades by this date.',
                'description_km' => 'បុគ្គលិក ត្រូវ ដាក់ ពិន្ទុ ចុង ក្រោយ នៅ ថ្ងៃ នេះ ។',
                'event_type' => 'academic_deadline',
                'start_date' => '2026-12-30',
                'is_all_day' => true,
                'audience' => 'faculty',
                'color_code' => '#dc3545',
                'is_active' => true,
                'sort_order' => 9,
            ],
            [
                'title_en' => 'Spring Semester 2027 Registration',
                'title_km' => 'ការចុះឈ្មោះឆមាសផ្សេងទៀត2027',
                'description_en' => 'Registration for Spring Semester 2027 opens.',
                'description_km' => 'ការចុះឈ្មោះសម្រាប់ឆមាសផ្សេងទៀត2027 បើក។',
                'event_type' => 'registration',
                'start_date' => '2027-01-05',
                'end_date' => '2027-01-25',
                'is_all_day' => true,
                'audience' => 'all',
                'color_code' => '#007bff',
                'is_active' => true,
                'sort_order' => 10,
            ],
            [
                'title_en' => 'Spring Semester 2027 Begins',
                'title_km' => 'ចាប់ផ្តើមឆមាស2027',
                'description_en' => 'First day of classes for Spring Semester 2027.',
                'description_km' => 'ថ្ងៃដំបូងនៃការសិក្សាសម្រាប់ឆមាស2027។',
                'event_type' => 'semester_start',
                'start_date' => '2027-02-01',
                'is_all_day' => true,
                'audience' => 'all',
                'color_code' => '#17a2b8',
                'is_active' => true,
                'sort_order' => 11,
            ],
            [
                'title_en' => 'Chinese New Year',
                'title_km' => 'បុណ្យចូលឆ្នាំថ្មី',
                'description_en' => 'Public holiday - Chinese New Year.',
                'description_km' => 'ថ្ងៃឈប់សាធារណៈ - បុណ្យចូលឆ្នាំថ្មី។',
                'event_type' => 'holiday',
                'start_date' => '2027-02-10',
                'end_date' => '2027-02-12',
                'is_all_day' => true,
                'audience' => 'all',
                'color_code' => '#28a745',
                'is_active' => true,
                'sort_order' => 12,
            ],
            [
                'title_en' => 'Annual Graduation Ceremony',
                'title_km' => 'ពិធីបញ្ចប់ការសិក្សាប្រចាំឆ្នាំ',
                'description_en' => 'Annual graduation ceremony for all degree programs.',
                'description_km' => 'ពិធីបញ្ចប់ការសិក្សាប្រចាំឆ្នាំសម្រាប់កម្មវិធីទាំងអស់។',
                'event_type' => 'graduation',
                'start_date' => '2027-03-15',
                'is_all_day' => true,
                'audience' => 'all',
                'color_code' => '#6610f2',
                'is_active' => true,
                'sort_order' => 13,
            ],
            [
                'title_en' => 'Law Society Conference 2027',
                'title_km' => 'សន្និសីទសមាគមច្បាប2027',
                'description_en' => 'Annual law society conference featuring guest speakers and workshops.',
                'description_km' => 'សន្និសីទប្រចាំឆ្នាំរបស់សមាគមច្បាប់ ដែលមានភ្ញៀវនិយតករនិងសិក្ខារកិច្ច។',
                'event_type' => 'special_event',
                'start_date' => '2027-04-20',
                'end_date' => '2027-04-22',
                'location' => 'Main Auditorium',
                'is_all_day' => false,
                'start_time' => '09:00:00',
                'end_time' => '17:00:00',
                'audience' => 'all',
                'color_code' => '#e83e8c',
                'is_active' => true,
                'sort_order' => 14,
            ],
            [
                'title_en' => 'Summer Break',
                'title_km' => 'ចន្រ្ទាក់រដូវកាល',
                'description_en' => 'Summer break for all students.',
                'description_km' => 'ចន្រ្ទាក់រដូវកាលសម្រាប់និស្សិតទាំងអស់។',
                'event_type' => 'holiday',
                'start_date' => '2027-05-01',
                'end_date' => '2027-07-31',
                'is_all_day' => true,
                'audience' => 'students',
                'color_code' => '#28a745',
                'is_active' => true,
                'sort_order' => 15,
            ],
        ];

        foreach ($events as $event) {
            if (in_array($event['event_type'], ['registration', 'orientation', 'semester_start', 'semester_end'])) {
                $event['program_id'] = null;
            } elseif ($programs->count() > 0 && rand(0, 1)) {
                $event['program_id'] = $programs->random()->id;
            }
            
            AcademicCalendar::create($event);
        }
    }
}
