<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\AlumniDonation;
use Carbon\Carbon;

class AlumniDonationSeeder extends Seeder
{
    public function run(): void
    {
        $donations = [
            [
                'alumni_id' => 1,
                'donation_type' => 'scholarship',
                'amount' => 500.00,
                'currency' => 'USD',
                'payment_method' => 'bank_transfer',
                'frequency' => 'one_time',
                'status' => 'completed',
                'transaction_id' => 'DON20241215001',
                'purpose' => 'Support for underprivileged law students',
                'purpose_km' => 'គាំទ្រដល់និស្សិតច្បាប់ដែលមានជំរាបសម្រាប់',
                'is_anonymous' => false,
                'message' => 'Giving back to the institution that shaped my career. I hope this helps future lawyers achieve their dreams.',
                'message_km' => 'ប្រគល់មកវិញដល់ស្ថាប័នដែលបានរចនាអាជីពរបស់ខ្ញុំ។ ខ្ញុំសង្ឃឹមថានេះនឹងជួយមេធាវីអនាគតឱ្យសម្រេចបំណងរបស់ពួកគេ។',
                'donation_date' => Carbon::parse('2024-12-15'),
                'created_at' => Carbon::now()->subMonths(1),
                'updated_at' => Carbon::now()->subMonths(1),
            ],
            [
                'alumni_id' => 2,
                'donation_type' => 'library',
                'amount' => 1000.00,
                'currency' => 'USD',
                'payment_method' => 'credit_card',
                'frequency' => 'monthly',
                'status' => 'recurring',
                'transaction_id' => 'DON20241120001',
                'purpose' => 'Legal textbook and resource acquisition',
                'purpose_km' => 'ការទិញសៀវភៅច្បាប់ និងធនធាន',
                'is_anonymous' => false,
                'message' => 'Investing in legal education resources for the next generation.',
                'message_km' => 'វិនិយោគក្នុងធនធានអប់រំច្បាប់សម្រាប់ជំនាន់ក្រោយ។',
                'donation_date' => Carbon::parse('2024-11-20'),
                'created_at' => Carbon::now()->subMonths(2),
                'updated_at' => Carbon::now()->subMonths(2),
            ],
            [
                'alumni_id' => 3,
                'donation_type' => 'moot_court',
                'amount' => 750.00,
                'currency' => 'USD',
                'payment_method' => 'bank_transfer',
                'frequency' => 'one_time',
                'status' => 'completed',
                'transaction_id' => 'DON20241010001',
                'purpose' => 'Moot court competition support',
                'purpose_km' => 'គាំទ្រការប្រកួត Moot Court',
                'is_anonymous' => true,
                'message' => '',
                'message_km' => '',
                'donation_date' => Carbon::parse('2024-10-10'),
                'created_at' => Carbon::now()->subMonths(3),
                'updated_at' => Carbon::now()->subMonths(3),
            ],
            [
                'alumni_id' => 1,
                'donation_type' => 'infrastructure',
                'amount' => 2000.00,
                'currency' => 'USD',
                'payment_method' => 'credit_card',
                'frequency' => 'annual',
                'status' => 'recurring',
                'transaction_id' => 'DON20240905001',
                'purpose' => 'Classroom technology enhancement',
                'purpose_km' => 'ការបង្កើនប្រសិទ្ធិភាពបច្ចេកវិទ្យាថ្នាក់រៀន',
                'is_anonymous' => false,
                'message' => 'Modern legal education requires modern technology. Happy to contribute to our alma mater.',
                'message_km' => 'ការអប់រំច្បាប់ទំនើបត្រូវការបច្ចេកវិទ្យាទំនើប។ រីករាយក្នុងការចូលរួមចំណាយដល់សាលារៀនចាស់របស់យើង។',
                'donation_date' => Carbon::parse('2024-09-05'),
                'created_at' => Carbon::now()->subMonths(4),
                'updated_at' => Carbon::now()->subMonths(4),
            ],
            [
                'alumni_id' => 5,
                'donation_type' => 'general',
                'amount' => 100.00,
                'currency' => 'USD',
                'payment_method' => 'cash',
                'frequency' => 'one_time',
                'status' => 'completed',
                'transaction_id' => 'DON20240815001',
                'purpose' => 'General development fund',
                'purpose_km' => 'មូលនិធិអភិវឌ្ឍទូទៅ',
                'is_anonymous' => false,
                'message' => 'Small contribution to support our law school\'s mission.',
                'message_km' => 'ការចូលរួមតូចតាច់ដើម្បីគាំទ្របេសកកម្មរបស់សាលាច្បាប់របស់យើង។',
                'donation_date' => Carbon::parse('2024-08-15'),
                'created_at' => Carbon::now()->subMonths(5),
                'updated_at' => Carbon::now()->subMonths(5),
            ],
            [
                'alumni_id' => 4,
                'donation_type' => 'research',
                'amount' => 300.00,
                'currency' => 'USD',
                'payment_method' => 'bank_transfer',
                'frequency' => 'one_time',
                'status' => 'completed',
                'transaction_id' => 'DON20240720001',
                'purpose' => 'Legal research and publication support',
                'purpose_km' => 'គាំទ្រស្រាវជ្រាវច្បាប់ និងការផ្សព្វផ្សាយ',
                'is_anonymous' => false,
                'message' => 'Supporting academic research that benefits Cambodia\'s legal development.',
                'message_km' => 'គាំទ្រការស្រាវជ្រាវសិក្សាដែលប្រយោជន៍ដល់ការអភិវឌ្ឍច្បាប់របស់កម្ពុជា។',
                'donation_date' => Carbon::parse('2024-07-20'),
                'created_at' => Carbon::now()->subMonths(6),
                'updated_at' => Carbon::now()->subMonths(6),
            ],
            [
                'alumni_id' => 2,
                'donation_type' => 'scholarship',
                'amount' => 1500.00,
                'currency' => 'USD',
                'payment_method' => 'credit_card',
                'frequency' => 'one_time',
                'status' => 'completed',
                'transaction_id' => 'DON20240610001',
                'purpose' => 'Women in Law Scholarship Fund',
                'purpose_km' => 'មូលនិធិអត្ថបទ្យកសិក្សាស្ត្រីក្នុងវិស័យច្បាប់',
                'is_anonymous' => false,
                'message' => 'Empowering women in legal education and profession.',
                'message_km' => 'ផ្តល់អំណាចដល់ស្ត្រីក្នុងការអប់រំច្បាប់ និងវិស័យជំនួញ។',
                'donation_date' => Carbon::parse('2024-06-10'),
                'created_at' => Carbon::now()->subMonths(7),
                'updated_at' => Carbon::now()->subMonths(7),
            ],
            [
                'alumni_id' => 3,
                'donation_type' => 'alumni_events',
                'amount' => 250.00,
                'currency' => 'USD',
                'payment_method' => 'bank_transfer',
                'frequency' => 'one_time',
                'status' => 'completed',
                'transaction_id' => 'DON20240505001',
                'purpose' => 'Alumni reunion and networking events',
                'purpose_km' => 'ពិធីប្រជុំនិស្សិតចាស់ និងព្រឹត្តិការណ៍បណ្តាញ',
                'is_anonymous' => false,
                'message' => 'Supporting alumni engagement and community building.',
                'message_km' => 'គាំទ្រការចូលរួមរបស់និស្សិតចាស់ និងការស្ថាបនាសហគមន៍។',
                'donation_date' => Carbon::parse('2024-05-05'),
                'created_at' => Carbon::now()->subMonths(8),
                'updated_at' => Carbon::now()->subMonths(8),
            ],
        ];

        foreach ($donations as $donation) {
            AlumniDonation::create($donation);
        }
    }
}