<?php

namespace Database\Seeders;

use App\Models\Article;
use App\Models\Category;
use App\Models\User;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ArticleSeeder extends Seeder
{
    public function run(): void
    {
        $author = User::where('email', 'admin@university.edu')->first() ?? User::first();
        $categories = Category::all()->keyBy('slug');

        $articles = [
            [
                'title_en' => 'NUM International Program of Legal Studies Welcomes First Cohort',
                'title_km' => 'កម្មវិធីអន្តរជាតិផ្នែកសិក្សាច្បាប់ NUM ស្វាគមន៍ការចូលរៀនជាលើកដំបូង',
                'content_en' => 'The NUM International Program of Legal Studies is proud to announce the successful enrollment of its first cohort of students. This landmark program represents a significant step forward in legal education in Cambodia, offering students a comprehensive curriculum that combines international legal standards with local context. The program has attracted talented students from across the nation and internationally, creating a diverse and vibrant learning community.',
                'content_km' => 'កម្មវិធីអន្តរជាតិផ្នែកសិក្សាច្បាប់ NUM មានការមោទនភាពក្នុងការប្រកាសអំពីការចុះឈ្មោះដោយជោគជ័យនៃការចូលរៀនជាលើកដំបូងរបស់ខ្លួន។ កម្មវិធីដ៏សំខាន់នេះធ្វើជាជំហានដ៏សំខាន់មួយក្នុងការអភិវឌ្ឍន៍ការសិក្សាច្បាប់នៅកម្ពុជា ផ្តល់និស្សិតនូវកម្មវិធីសិក្សាដ៏ទូលំទូលាយដែលរួមបញ្ចូលគោលការណ៍ច្បាប់អន្តរជាតិជាមួយបរិបទមូលដ្ឋាន។',
                'excerpt_en' => 'The NUM International Program of Legal Studies welcomes its first cohort of students, marking a new era in Cambodian legal education.',
                'excerpt_km' => 'កម្មវិធីអន្តរជាតិផ្នែកសិក្សាច្បាប់ NUM ស្វាគមន៍និស្សិតជាលើកដំបូង ដែលជាយុគសម័យថ្មីក្នុងការសិក្សាច្បាប់នៅកម្ពុជា។',
                'category' => 'news-and-announcements',
                'is_featured' => true,
                'published_at' => now()->subDays(1),
            ],
            [
                'title_en' => 'Partnership with International Law Universities Announced',
                'title_km' => 'ប្រកាសភាពជាដៃគូជាមួយសាកលវិទ្យាល័យច្បាប់អន្តរជាតិ',
                'content_en' => 'NUM International Program of Legal Studies is thrilled to announce strategic partnerships with several renowned international law universities. These partnerships will provide students with exchange opportunities, joint research programs, and access to international legal resources. Partner institutions include universities from the United Kingdom, Australia, and Southeast Asia.',
                'content_km' => 'កម្មវិធីអន្តរជាតិផ្នែកសិក្សាច្បាប់ NUM មានការរំភើបក្នុងការប្រកាសពីភាពជាដៃគូយុទ្ធសាស្ត្រជាមួយសាកលវិទ្យាល័យច្បាប់អន្តរជាតិមួយចំនួនដែលមានកេរ្តិ៍ឈ្នះ។ ភាពជាដៃទាំងនេះនឹងផ្តល់ឱកាសនិស្សិតក្នុងការផ្លាស់ប្8តូរ កម្មវិធីស្រាវជ្រាវរួម និងការចូលដំណឹងធនធានច្បាប់អន្9រជាតិ។',
                'excerpt_en' => 'Strategic partnerships with international law universities to provide exchange opportunities and joint research programs.',
                'excerpt_km' => 'ភាពជាដៃគូយុទ្ធសាស្ត្រជាមួយសាកលវិទ្យាល័យច្បាប់អន្9រជាតិ ដើម្បីផ្តល់ឱកាសផ្លាស់ប្8តូរ និងកម្មវិធីស្រាវជ្រាវរួម។',
                'category' => 'news-and-announcements',
                'is_featured' => true,
                'published_at' => now()->subDays(3),
            ],
            [
                'title_en' => 'Student Wins International Moot Court Competition',
                'title_km' => 'និស្សិតឈ្នះការប្រកួតតុលាការមិនពិតអន្�រជាតិ',
                'content_en' => 'A student from NUM International Program of Legal Studies has won first place in the prestigious International Moot Court Competition. This remarkable achievement demonstrates the high quality of legal education at NUM and the dedication of our students. The competition tested students skills in legal reasoning, argumentation, and courtroom advocacy.',
                'content_km' => 'និស្សិតម្នាក់ពីកម្មវិធីអន្9រជាតិ NUM បានឈ្នះចំណាត់ថ្នាក់លេខ១ក្នុងការប្រកួតតុលាការមិនពិតអន្9រជាតិ។ សមិទ្ធិផលដ៏គួរឱ្យកត់សម្គាល់នេះបង្ហាញពីគុណភាពខ្ពស់នៃការសិក្សាច្បាប់នៅ NUM និងការប្តេជ្ញាចិត្តរបស់និស្សិតយើង។',
                'excerpt_en' => 'NUM student achieves first place in International Moot Court Competition, showcasing exceptional legal skills.',
                'excerpt_km' => 'និស្សិត NUM ឈ្នះចំណាត់ថ្នាក់ទី១ក្នុងការប្រកួតតុលាការមិនពិតអន្9រជាតិ បង្ហាញពីជំនាញច្បាប់ពិសេស។',
                'category' => 'student-life',
                'is_featured' => true,
                'published_at' => now()->subDays(5),
            ],
            [
                'title_en' => 'New Research Center for International Law Established',
                'title_km' => 'បង្កើតមជ្ឈមណ្ឌលស្រាវជ្រាវថ្មីសម្រាប់ច្បាប់អន្�រជាតិ',
                'content_en' => 'NUM International Program of Legal Studies is proud to announce the establishment of a new Research Center for International Law. The center will focus on comparative legal studies, international trade law, human rights law, and environmental law. It will serve as a hub for scholars and practitioners to engage in cutting-edge legal research.',
                'content_km' => 'កម្មវិធីអន្9រជាតិ NUM មានការមោទនភាពក្នុងការប្រកាសពីការបង្កើតមជ្ឈមណ្ឌលស្រាវជ្រាវថ្មីសម្រាប់ច្បាប់អន្9រជាតិ។ មជ្ឈមណ្ឌលនេះនឹងផ្តោតលើការសិក្សាច្បាប់ប្រៀបធៀប ច្បាប់ពាណិជ្ជកម្មអន្9រជាតិ ច្បាប់សិទ្ធិមនុស្ស និងច្បាប់បរិស្ថាន។',
                'excerpt_en' => 'New Research Center for International Law to focus on comparative legal studies and human rights law.',
                'excerpt_km' => 'មជ្ឈមណ្ឌលស្រាវជ្រាវថ្មី សម្រាប់ច្បាប់អន្9រជាតិ ផ្តោតលើការសិក្សាច្បាប់ប្រៀបធៀប និងច្បាប់សិទ្ធិមនុស្ស។',
                'category' => 'research-and-publications',
                'is_featured' => false,
                'published_at' => now()->subDays(7),
            ],
            [
                'title_en' => 'Internship Program with Supreme Court Announced',
                'title_km' => 'ប្រកាសកម្មវិធីកម្មសិក្សាជាមួយតុលាការកំពូល',
                'content_en' => 'NUM International Program of Legal Studies is excited to announce a new internship program with the Supreme Court of Cambodia. This program will provide students with hands-on experience in the judicial system, allowing them to observe court proceedings and work with experienced judges.',
                'content_km' => 'កម្មវិធីអន្9រជាតិ NUM មានការរំភើបក្នុងការប្រកាសពីកម្មវិធីកម្មសិក្សាថ្មី ជាមួយតុលាការកំពូលនៃប្រទេសកម្ពុជា។ កម្មវិធីនេះនឹងផ្តល់ឱកាសនិស្សិត នូវបទពិសោធន៍ជាក់ស្8តែង នៃប្រព័ន្ធតុលាការ អនុញ្ញាត ឱកាស ឱ្យ ពួក គេ ធ្វើ ការ សង្កេត នៃ ការ ក្តី និង ធ្វើ ការ ជា មួយ ចៅ ក្រម ដ៏ មាន បទ ពិ ស ោ ធ ន៍ ។',
                'excerpt_en' => 'New internship program with Supreme Court provides students hands-on experience in the judicial system.',
                'excerpt_km' => 'កម្មវិធីកម្មសិក្សាថ្មី ជាមួយតុលាការកំពូល ផ្8តល់ ប ទ ព ិ ស ោ ធ ន ៍ ជ ា ក ស ្ ត ែ ង ន ៃ ប ្ រ ព ន ្ យ ត ុ ល ា ក ា រ ។',
                'category' => 'academic-programs',
                'is_featured' => false,
                'published_at' => now()->subDays(10),
            ],
            [
                'title_en' => 'Distinguished Lecture Series: Justice at the International Criminal Court',
                'title_km' => 'ស៊េរីមេទ្យារដ្ឋមន្8្រី ៖ យុត្8តិធម៌នៅតុលាការពិសេសអន្9រជាតិ',
                'content_en' => 'NUM International Program of Legal Studies is hosting a distinguished lecture series featuring judges and prosecutors from the International Criminal Court. This event will provide students with unique insights into international criminal law and the pursuit of justice for mass atrocities.',
                'content_km' => 'កម្មវិធីអន្9រជាតិ NUM កំពុង រៀប ចំ ស ៊េ រ ី ម ួ យ ម េ ទ ្ យ ា រ ដ ្ ឋ ម ន ្ ត ្ រ ី ដ ែ ល ម ា ន ចៅ ក្ រ ម ន ិ ង ច ច ប ធ រ ហ ា រ ព ី ត ុ ល ា ក ា រ ព ិ ស ទ ្ យ អ ន ្ ត រ ជ ា ត ិ ។',
                'excerpt_en' => 'Distinguished lecture series featuring ICC judges and prosecutors on international criminal law.',
                'excerpt_km' => ' ស ៊េ រ ី ម ួ យ ម េ ទ ្ យ ា រ ដ ្ ឋ ម ន ្ ត ្ រ ី ដ ែ ល ម ា ន ច ច ក រ ម ICC ន ិ ង ច ច ប ធ រ ហ ា រ ព ី ច ប ា ប ពេទ ្ យ អ ន ្ ត រ ជ ា ត ិ ។',
                'category' => 'events-and-seminars',
                'is_featured' => true,
                'published_at' => now()->subDays(12),
            ],
            [
                'title_en' => 'Alumni Success Story: From NUM to International Law Firm',
                'title_km' => 'រឿង ជ ោ គ ជ ័ យ រ ហ ស ត អ ត ន ត ា ល ង ក ៖ ព ី NUM ទ ៅ ក្ រ ុ ម ហ ៊ ុ ន ច ប ា ប អ ន ្ ត រ ជ ា ត ិ',
                'content_en' => 'Our alumnus, Sokha Meas, shares his journey from the NUM International Program of Legal Studies to becoming a senior associate at a prestigious international law firm in Singapore. He credits the program rigorous curriculum and international perspective for his success in the competitive legal field.',
                'content_km' => ' អ ត ន ត ា ល ង ក រ ប ស យ ើ ត ស ុ ខ ម ា ស ច ហ រ រ ដ ុ ប ដ ភ រ រ ត ប ស ហ ស រ ប ស រ ប យ ើ ត ព ី ក ម វ ិ ធ ី អ ន ្ ត រ ជ ា ត ិ NUM ទ ៅ ក ្ ល ា យ ជ ា អ ន ប ច ប ា ប ជ ា ន ់ ខ ព ស ស ន ន ន រ ប ស យ ើ ត ស ិ ង ហ ប ុ រ ី ។',
                'excerpt_en' => 'Alumni success story showcasing the career path from NUM to international law practice.',
                'excerpt_km' => ' រ ឿ ង ជ ោ គ ជ ័ យ អ ត ន ត ា ល ង ក ប ង ហ ា ញ ព ី ផ ល ូ វ អ ា ជ ី ព ព ី NUM ទ ៅ ក ា រ អ ន ុ វ ត រ ច ប ា ប អ ន ្ ត រ ជ ា ត ិ ។',
                'category' => 'news-and-announcements',
                'is_featured' => false,
                'published_at' => now()->subDays(14),
            ],
            [
                'title_en' => 'Workshop on Legal Writing and Research Skills',
                'title_km' => ' ស ិ ក ខ ា ស ា ល ា អ ន ុ ព ី ក ា រ ស រ សេ រ ច ប ា ប ន ិ ង ជ ំ ន ា ញ ស រ វ ជ ំ រ ា វ',
                'content_en' => 'NUM International Program of Legal Studies is organizing a comprehensive workshop on legal writing and research skills. The workshop will cover legal analysis, memorandum writing, brief preparation, and research methodologies. Led by experienced legal professionals, this training will help students develop essential skills for their legal careers.',
                'content_km' => ' ក ម វ ិ ធ ី អ ន ្ ត រ ជ ា ត ិ NUM ក ត ព ុ ង រ រ ប ច រ ច យ ស ិ ក ខ ា ស ា ល ា ដ ៏ ទ ូ ល ំ ទ ូ ល ា យ អ ន ុ ព ី ជ ំ ន ា ញ ក ា រ ស រ សេ រ ច ប ា ប ន ិ ង ស រ វ ជ ំ រ ា វ ។',
                'excerpt_en' => 'Comprehensive workshop on legal writing and research skills for law students.',
                'excerpt_km' => ' ស ិ ក ខ ា ស ា ល ា ទ ូ ល ំ ទ ូ ល ា យ អ ន ុ ព ី ជ ំ ន ា ញ ក ា រ ស រ សេ រ ច ប ា ប ន ិ ង ស រ វ ជ ំ រ ា វ ស ម ្ រ ា ប ន ិ ស ធ ស ត ច ប ា ប ។',
                'category' => 'events-and-seminars',
                'is_featured' => false,
                'published_at' => now()->subDays(15),
            ],
            [
                'title_en' => 'Call for Applications: International Law Summer School',
                'title_km' => ' ហ ៅ ក ា រ ដ ា ក ច ព ា ក យ ៖ ស ា ល ា រ ា ជ យ ច ប ា ប អ ន ្ ត រ ជ ា ត ិ',
                'content_en' => 'NUM International Program of Legal Studies invites applications for our International Law Summer School. The program will be held in partnership with the University of Melbourne and will cover international trade law, human rights law, and international arbitration.',
                'content_km' => ' ក ម វ ិ ធ ី អ ន ្ ត រ ជ ា ត ិ NUM អ ញ ជ ើ ញ ក ា រ ដ ា ក ច ព ា ក យ ស ម ្ រ ា ប ន ស ា ល ា រ ា ជ យ ច ប ា ប អ ន ្ ត រ ជ ា ត ិ រ ប ស យ ើ ត ។',
                'excerpt_en' => 'Apply now for the International Law Summer School in partnership with University of Melbourne.',
                'excerpt_km' => ' ដ ា ក ច ព ា ក យ ឥ ឡ ូ វ ស ម ្ រ ា ប ន ស ា ល ា រ ា ជ យ ច ប ា ប អ ន ្ ត រ ជ ា ត ិ ក ន ុ ង ភ ា ព ជ ា ដ ឃ គ ូ ជ ា ម ួ យ ស ា ក ល វ ិ ទ ្ យ ា ល ័ យ Melbourne ។',
                'category' => 'academic-programs',
                'is_featured' => false,
                'published_at' => now()->subDays(18),
            ],
            [
                'title_en' => 'Guest Lecture: Human Rights Law in Southeast Asia',
                'title_km' => ' ម េ ទ ្ យ ា រ ដ ្ ឋ ម ន ្ ត ្ រ ៖ ច ប ា ប ស ិ ទ ្ ធ ិ ម ន ុ ស ស ន អ ា ស ី អ ា គ ្ ន ច់',
                'content_en' => 'Join us for a guest lecture on Human Rights Law in Southeast Asia, delivered by Professor David Williams from Cornell Law School. This lecture will explore the regional mechanisms for human rights protection and the challenges facing human rights advocacy in the ASEAN region.',
                'content_km' => ' ច ូ ល រ ួ ម ជ ា ម ួ យ យ ើ ង ស ម ្ រ ា ប ន ម េ ទ ្ យ ា រ ដ ្ ឋ ម ន ្ ត ្ រ អ ន ុ ព ី ច ប ា ប ស ិ ទ ្ ធ ិ ម ន ុ ស ស ន អ ា ស ី អ ា គ ្ ន ច់ ។',
                'excerpt_en' => 'Guest lecture on human rights law in Southeast Asia by Professor David Williams.',
                'excerpt_km' => ' ម េ ទ ្ យ ា រ ដ ្ ឋ ម ន ្ ត ្ រ អ ន ុ ព ី ច ប ា ប ស ិ ទ ្ ធ ិ ម ន ុ ស ស ន អ ា ស ី អ ា គ ្ ន ច់ ។',
                'category' => 'events-and-seminars',
                'is_featured' => false,
                'published_at' => now()->subDays(20),
            ],
            [
                'title_en' => 'Student Research Published in International Journal',
                'title_km' => ' ក ា រ ស រ វ ជ ំ រ ា វ រ ហ ស ន ិ ស ធ ស ត ត ្ រ ូ វ ប ើ ក ព ុ ម ធ ព ក ន ុ ង ទ ស ន ា វ ដ ត ី អ ន ្ ត រ ជ ា ត ិ',
                'content_en' => 'A research paper written by NUM International Program students has been published in the International Journal of Law and Justice. The paper examines the challenges of implementing international trade agreements in Cambodia and offers recommendations for policy reform.',
                'content_km' => ' ក រ ដ ី ស រ វ ជ ំ រ ា វ ម ួ យ ដ គ ល ស រ សេ រ ដ ង ន ិ ស ធ ស ត ក ម វ ិ ធ ី អ ន ្ ត រ ជ ា ត ិ NUM ត ្ រ ូ វ ប ើ ក ព ុ ម ធ ព ក ន ុ ង International Journal of Law and Justice ។',
                'excerpt_en' => 'Student research paper published in International Journal of Law and Justice.',
                'excerpt_km' => ' ក រ ដ ី ស រ វ ជ ំ រ ា វ រ ហ ស ន ិ ស ធ ស ត ត ្ រ ូ វ ប ើ ក ព ុ ម ធ ព ក ន ុ ង International Journal of Law and Justice ។',
                'category' => 'research-and-publications',
                'is_featured' => false,
                'published_at' => now()->subDays(22),
            ],
            [
                'title_en' => 'Legal Aid Clinic Opens at NUM Campus',
                'title_km' => ' គ េ ហ ទ ព ថ រ ជ ួ យ ច ប ា ប ប ើ ក ន អ វ ា ល NUM',
                'content_en' => 'NUM International Program of Legal Studies is proud to announce the opening of a Legal Aid Clinic on campus. The clinic will provide free legal advice to underserved communities while offering students practical experience in legal practice.',
                'content_km' => ' ក ម វ ិ ធ ី អ ន ្ ត រ ជ ា ត ិ NUM ម ា ន ក ា រ ម ូ ទ ន ភ ា ព ក ន ុ ង ក ា រ ប ធ ក ា ស ព ី ក ា រ ប ើ ក គ េ ហ ទ ព ថ រ ជ ួ យ ច ប ា ប ន អ វ ា ល ។',
                'excerpt_en' => 'New Legal Aid Clinic provides free legal advice to communities while offering student practical experience.',
                'excerpt_km' => ' គ េ ហ ទ ព ថ រ ជ ួ យ ច ប ា ប ថ ធ ម ី ផ ល ើ ក ា រ ប រ ទ ស រ ច ប ា ប ឥ ត គ ល ស ហ គ ម ន ៍ ខ ណ ៈ ព ឹ ត ដ ល ប ទ ព ិ ស ោ ធ ន ៍ ជ ា ក ់ ស ល ់ ឲ ន ា ។',
                'category' => 'student-life',
                'is_featured' => false,
                'published_at' => now()->subDays(25),
            ],
            [
                'title_en' => 'Professor Wins Prestigious International Legal Award',
                'title_km' => ' ប ណ ឌ ិ ត ឈ ន ជ ា យ ស ន ា ង អ ន ុ គ ទ ី ម ន ្ ត ្ រ ័ យ ច ប ា ប ន ់ ល ើ ខ ា ង ច ប ា ប អ ន ុ វ ត ្ ត ជ ា ន ់ អ ន ្ ត រ ជ ា ត ិ',
                'content_en' => 'Professor Chanrithy Ith, faculty member at NUM International Program of Legal Studies, has been awarded the prestigious International Law Award by the International Law Association. The award recognizes Professor Ith significant contributions to international human rights law.',
                'content_km' => ' ប ណ ឌ ិ ត ច ន រ ិ ទ ្ យ អ ិ ត ស ា ន ុ រ ដេ ី ម ន ្ ត ្ រ ស ា យ ភ ា ព ន ់ ក ម វ ិ ធ ី អ ន ្ ត រ ជ ា ត ិ NUM ត ្ រ ូ វ ប ា ន រ ង រ ស ន ា ង អ ន ុ គ ទ ី ម ន ្ ត ្ រ ័ យ ច ប ា ប ន ់ ល ើ ខ ា ង ច ប ា ប ព ី ស ម ា គ ម ច ប ា ប អ ន ្ ត រ ជ ា ត ិ ។',
                'excerpt_en' => 'Professor Chanrithy Ith receives International Law Award for contributions to human rights law.',
                'excerpt_km' => ' ប ណ ឌ ិ ត ច ន រ ិ ទ ្ យ អ ិ ត ស ា ន ុ រ ដេ ី ម ទ ទ ួ ល ប រ ង រ ស ន ា ង ច ប ា ប អ ន ្ ត រ ជ ា ត ិ ស ម រ ា ប ន ក ា រ រ ួ ម ច ប ា ប ទ ា យ ក ណ ្ ត ត ហ ង ់ ។',
                'category' => 'faculty-achievements',
                'is_featured' => true,
                'published_at' => now()->subDays(28),
            ],
            [
                'title_en' => 'Mock Trial Competition Winners Announced',
                'title_km' => ' ប ង ្ ក ា រ ឈ ន ល ទ ្ យ ក ា រ ប ធ រ ក ួ ត ត ុ ល ា ក ា រ ម ិ ន ព ិ ត',
                'content_en' => 'Congratulations to the winners of the annual Mock Trial Competition organized by NUM International Program of Legal Studies. The competition attracted teams from universities across Cambodia, with the final round judged by senior judges from the Cambodian courts.',
                'content_km' => ' ស ូ ម អ ប អ រ គ ុ ណ ដ ល ឈ ន ល ទ ្ យ ន ា ង ប ង ្ ក ា រ ប ធ រ ក ួ ត ត ុ ល ា ក ា រ ម ិ ន ព ិ ត ប ធ រ ច ា រ ស ា ធ ុ ក ម ្ ម វ ិ ធ ី NUM ។',
                'excerpt_en' => 'Winners announced for annual Mock Trial Competition with teams from across Cambodia.',
                'excerpt_km' => ' ឈ ន ល ទ ្ យ ត ្ រ ូ វ ប ា ន ប ង ្ ក ា រ ប ធ រ ក ួ ត ត ុ ល ា ក ា រ ម ិ ន ព ិ ត ប ធ រ ច ា រ ស ា ធ ុ ក ម ្ ម វ ិ ធ ី ព ី ស ា ក ល វ ិ ទ ្ យ ា ល ័ យ ទ ៅ យ ៈ ទ ្ យ ា ស ា ធ ុ ក ម ្ ព ុ ជ ា ។',
                'category' => 'student-life',
                'is_featured' => false,
                'published_at' => now()->subDays(30),
            ],
            [
                'title_en' => 'New Curriculum Emphasizes Practical Legal Skills',
                'title_km' => ' ក ម ្ ម វ ិ ធ ី ស ិ ក ្ ស ា ថ ្ ម ី ផ ង រ ម ា រ ជ ា ន ់ ជ ន ា រ ភ ា ព ច ្ ប ា ប ់ ជ ា ក ់ ជ ា ន ់ ប ្ រ ឹ ក ្ ស ា',
                'content_en' => 'NUM International Program of Legal Studies has unveiled a revised curriculum that emphasizes practical legal skills. The new program includes mandatory clinical placements, moot court exercises, and professional development workshops.',
                'content_km' => ' ក ម វ ិ ធ ី អ ន ្ ត រ ជ ា ត ិ NUM ប ា ន ប ើ ក ក ម ្ ម វ ិ ធ ី ស ិ ក ្ ស ា ដ ដ ឺ ក ម ្ ម វ ិ ធ ី ដ ដ ឺ ក ដ ើ ន ដ ើ ន ភ ា ព ប ្ រ ឹ ក ្ ស ា ច ្ ប ា ប ់ ។',
                'excerpt_en' => 'Revised curriculum emphasizes practical legal skills with clinical placements and moot court exercises.',
                'excerpt_km' => ' ក ម ្ ម វ ិ ធ ី ស ិ ក ្ ស ា ដ ដ ឺ ក ផ ង រ ម ា រ ជ ា ន ់ ជ ន ា រ ភ ា ព ច ្ ប ា ប ់ ជ ា ក ់ ជ ា ន ់ ប ្ រ ឹ ក ្ ស ា ។',
                'category' => 'academic-programs',
                'is_featured' => false,
                'published_at' => now()->subDays(35),
            ],
            [
                'title_en' => 'Exchange Program with National University of Singapore',
                'title_km' => ' ក ម ្ ម វ ិ ធ ី ផ ្ ល ា ស ប ្ ត ូ រ ជ ា ម ួ យ ស ា ក ល វ ិ ទ ្ យ ា ល ័ យ ស ិ ង ក ុ ណ ូ ប',
                'content_en' => 'NUM International Program of Legal Studies is pleased to announce a new student exchange program with the National University of Singapore. Students will have the opportunity to study at NUS for one semester, taking courses in international law and Asian legal systems.',
                'content_km' => ' ក ម វ ិ ធ ី អ ន ្ ត រ ជ ា ត ិ NUM ម ា ន ក ា រ រ ី ក រ ា យ ក ន ុ ង ស ា ន ុ រ ដ ោ ល ដ ល រ ប ស យ ើ ត ក ម ្ ម វ ិ ធ ី ផ ្ ល ា ស ប ្ ត ូ រ ន ិ ្ យ ស ា ក ល វ ិ ទ ្ យ ា ល ័ យ ជ ា ត ិ ស ិ ង ក ុ ណ ូ ប ។',
                'excerpt_en' => 'New exchange program with National University of Singapore for second-year students.',
                'excerpt_km' => ' ក ម ្ ម វ ិ ធ ី ផ ្ ល ា ស ប ្ ត ូ រ ថ ្ ម ី ជ ា ម ួ យ ស ា ក ល វ ិ ទ ្ យ ា ល ័ យ ជ ា ត ិ ស ិ ង ក ុ ណ ូ ប ។',
                'category' => 'academic-programs',
                'is_featured' => false,
                'published_at' => now()->subDays(40),
            ],
            [
                'title_en' => 'Legal Career Fair Connects Students with Employers',
                'title_km' => ' ព ិ ធ ី ក ា រ ង ្ ហ ា ត រ អ ា ជ ី ព ច ្ ប ា ប ់ ភ ា គ ច ន ិ ស ធ ស ិ ត ជ ា ម ួ យ ន ិ ក ុ ណ ូ ស ូ ប ្ រ ទ ៀ ស ់',
                'content_en' => 'NUM International Program of Legal Studies hosted its annual Legal Career Fair, bringing together leading law firms, corporate legal departments, and government agencies. Students had the opportunity to network with potential employers.',
                'content_km' => ' ក ម វ ិ ធ ី អ ន ្ ត រ ជ ា ត ិ NUM ប ា ន ប ើ ក ព ិ ធ ី ក ា រ ង ្ ហ ា ត រ អ ា ជ ី ព ច ្ ប ា ប ់ ប ្ រ ច ា រ ។',
                'excerpt_en' => 'Annual Legal Career Fair connects students with leading law firms and employers.',
                'excerpt_km' => ' ព ិ ធ ី ក ា រ ង ្ ហ ា ត រ អ ា ជ ី ព ច ្ ប ា ប ់ ប ្ រ ច ា រ ស ា ធ ុ ក ម ្ ម វ ិ ធ ី ន ិ ស ធ ស ិ ត ។',
                'category' => 'events-and-seminars',
                'is_featured' => false,
                'published_at' => now()->subDays(45),
            ],
            [
                'title_en' => 'Seminar on International Trade Law and WTO',
                'title_km' => ' ស ិ ក ្ ខ ា ស ា ល ា អ ំ ព ី ច ប ា ប ់ ព ា ណ ិ ជ ក ម ្ ម អ ន ្ ត រ ជ ា ត ិ ន ិ ង ល ើ WTO',
                'content_en' => 'Join us for a comprehensive seminar on International Trade Law and the World Trade Organization. The session will be led by Dr. Maria Santos, a WTO legal affairs expert, and will cover topics including trade dispute resolution and WTO agreements.',
                'content_km' => ' ច ូ ល រ ួ ម ជ ា ម ួ យ យ ើ ង ស ម ្ រ ា ប ន ិ ក ្ ខ ា ស ា ល ា ទ ូ ល ំ ទ ូ ល ា យ អ ំ ព ី ច ប ា ប ់ ព ា ណ ិ ជ ក ម ្ ម អ ន ្ ត រ ជ ា ត ិ ។',
                'excerpt_en' => 'Seminar on International Trade Law and the World Trade Organization by Dr. Maria Santos.',
                'excerpt_km' => ' ស ិ ក ្ ខ ា ស ា ល ា អ ំ ព ី ច ប ា ប ់ ព ា ណ ិ ជ ក ម ្ ម អ ន ្ ត រ ជ ា ត ិ ន ិ ង ល ើ WTO ។',
                'category' => 'events-and-seminars',
                'is_featured' => false,
                'published_at' => now()->subDays(48),
            ],
            [
                'title_en' => 'Human Rights Law Workshop for Students',
                'title_km' => ' ស ិ ក ្ ខ ា ស ា ល ា ច ប ា ប ់ ស ិ ទ ្ ធ ិ ម ន ុ ស ស ន ស ម ្ រ ា ប ន ិ ស ធ ស ត',
                'content_en' => 'NUM International Program of Legal Studies is organizing a comprehensive workshop on Human Rights Law. Students will learn about international human rights mechanisms, domestic implementation, and practical skills for human rights advocacy.',
                'content_km' => ' ក ម វ ិ ធ ី អ ន ្ ត រ ជ ា ត ិ NUM ក ត ព ុ ង រ រ ប ច រ ច យ ស ិ ក ្ ខ ា ស ា ល ា ទ ូ ល ំ ទ ូ ល ា យ អ ន ុ ព ី ច ប ា ប ់ ស ិ ទ ្ ធ ិ ម ន ុ ស ស ន ។',
                'excerpt_en' => 'Comprehensive workshop on Human Rights Law for law students.',
                'excerpt_km' => ' ស ិ ក ្ ខ ា ស ា ល ា ទ ូ ល ំ ទ ូ ល ា យ អ ន ុ ព ី ច ប ា ប ់ ស ិ ទ ្ ធ ិ ម ន ុ ស ស ន ។',
                'category' => 'events-and-seminars',
                'is_featured' => false,
                'published_at' => now()->subDays(50),
            ],
            [
                'title_en' => 'Environmental Law Research Initiative Launched',
                'title_km' => ' ប ង ្ ក ា រ គ ម ធ យ ក � រ ស រ វ ជ ំ រ ា វ ច ប ា ប ់ ប រ � ស ធ ថ ា ន',
                'content_en' => 'NUM International Program of Legal Studies has launched a new research initiative focused on environmental law in Cambodia. The project will examine legal frameworks for environmental protection and sustainable development.',
                'content_km' => ' ក ម វ ិ ធ ី អ ន ្ ត រ ជ ា ត ិ NUM ប ា ន ប ើ ក គ ម ធ យ ក � រ ស រ វ ជ ំ រ ា វ ថ ធ ម ី ថ ន ម ួ យ ផ ង រ ម ា រ ល ើ ច ប ា ប ់ ប រ � ស ធ ថ ា ន ន ន ប ្ ទេ ស ម ្ រ ា ប ់ ក ម ព ុ ជ ា ។',
                'excerpt_en' => 'New research initiative focused on environmental law in Cambodia.',
                'excerpt_km' => ' គ ម ធ យ ក � រ ស រ វ ជ ំ រ ា វ ថ ធ ម ី ថ ន ម ួ យ ផ ង រ ម ា រ ល ើ ច ប ា ប ់ ប រ � ស ធ ថ ា ន ន ន ប ្ ទេ ស ។',
                'category' => 'research-and-publications',
                'is_featured' => false,
                'published_at' => now()->subDays(52),
            ],
            [
                'title_en' => 'Student Ambassadors Program Launched',
                'title_km' => ' ប ង ្ ក ា រ ក ម វ ិ ធ ី ស ា ន ុ រ ដ ោ ល ន ិ ស ធ ស ត អ ន ម ួ យ',
                'content_en' => 'NUM International Program of Legal Studies is proud to announce the launch of our Student Ambassadors Program. This program will select outstanding students to represent the program at events and recruit future students.',
                'content_km' => ' ក ម វ ិ ធ ី អ ន ្ ត រ ជ ា ត ិ NUM ម ា ន ក ា រ ម ូ ទ ន ភ ា ព ក ន ុ ង ក ា រ ប ង ្ ក ា រ ក ម វ ិ ធ ី ស ា ន ុ រ ដ ោ ល ន ិ ស ធ ស ត ។',
                'excerpt_en' => 'New Student Ambassadors Program to represent NUM at events and recruit future students.',
                'excerpt_km' => ' ក ម វ ិ ធ ី ស ា ន ុ រ ដ ោ ល ន ិ ស ធ ស ត ថ ធ ម ី ថ ន ម ួ យ ដ ើ ន ល ើ ក ា រ រ ួ ម ម ុ ខ ន ិ ង ល ើ ព្រ ឹ ត ធ ី វ ុ ល ។',
                'category' => 'student-life',
                'is_featured' => false,
                'published_at' => now()->subDays(55),
            ],
            [
                'title_en' => 'International Arbitration Workshop',
                'title_km' => ' ស ិ ក ្ ខ ា ស ា ល ា អ ភ ិ ប ា ល ក ិ ច ធ ន ទ ស ម ូ យ អ ន ្ ត រ ជ ា ត ិ',
                'content_en' => 'Join us for an intensive workshop on International Arbitration led by experts from leading international law firms. Learn about arbitration procedures, drafting arbitration agreements, and representing clients in international disputes.',
                'content_km' => ' ច ូ ល រ ួ ម ជ ា ម ួ យ យ ើ ង ស ម ្ រ ា ប ន ស ិ ក ្ ខ ា ស ា ល ា អ ភ ិ ប ា ល ក ិ ច ធ ន ទ ស ម ូ យ អ ន ្ ត រ ជ ា ត ិ ។',
                'excerpt_en' => 'Intensive workshop on International Arbitration led by international law experts.',
                'excerpt_km' => ' ស ិ ក ្ ខ ា ស ា ល ា អ ភ ិ ប ា ល ក ិ ច ធ ន ទ ស ម ូ យ អ ន ្ ត រ ជ ា ត ិ ។',
                'category' => 'events-and-seminars',
                'is_featured' => false,
                'published_at' => now()->subDays(58),
            ],
            [
                'title_en' => 'Legal English Certification Program',
                'title_km' => ' ក ម វ ិ ធ ី វ ិ ធ យ ស ា ន ុ ច ប ា ប ភ ា ស ា ន អ ង គ ល ី ស',
                'content_en' => 'NUM International Program of Legal Studies is offering a new Legal English Certification Program. This program will help students develop the English language skills necessary for international legal practice.',
                'content_km' => ' ក ម វ ិ ធ ី អ ន ្ ត រ ជ ា ត ិ NUM ក ត ព ុ ង រ ផ ល ើ ក ម វ ិ ធ ី វ ិ ធ យ ស ា ន ុ ច ប ា ប ភ ា ស ា ន អ ង គ ល ី ស ។',
                'excerpt_en' => 'New Legal English Certification Program for international legal practice.',
                'excerpt_km' => ' ក ម វ ិ ធ ី វ ិ ធ យ ស ា ន ុ ច ប ា ប ភ ា ស ា ន អ ង គ ល ី ស ថ ធ ម ី ថ ន ម ួ យ ។',
                'category' => 'academic-programs',
                'is_featured' => false,
                'published_at' => now()->subDays(60),
            ],
            [
                'title_en' => 'Comparative Constitutional Law Symposium',
                'title_km' => ' ស ន ្ ន ិ ស ី ទ ច ប ា ប ់ រ ដ ្ ឋ ធ ម ្ រ ន � ញ ធ ា រ ស ា ន ុ ប ្ រ ល ើ ប ្ រ ួ ម',
                'content_en' => 'NUM International Program of Legal Studies will host a symposium on Comparative Constitutional Law. Scholars from around the world will present research on constitutional systems and human rights protections.',
                'content_km' => ' ក ម វ ិ ធ ី អ ន ្ ត រ ជ ា ត ិ NUM ន ឹ ង រ ួ ម ម ុ ខ ស ន ្ ន ិ ស ី ទ ច ប ា ប ់ រ ដ ្ ឋ ធ ម ្ រ ន � ញ ធ ា រ ។',
                'excerpt_en' => 'Symposium on Comparative Constitutional Law with international scholars.',
                'excerpt_km' => ' ស ន ្ ន ិ ស ី ទ ច ប ា ប ់ រ ដ ្ ឋ ធ ម ្ រ ន � ញ ធ ា រ ជ ា ម ួ យ អ ន ្ ត រ ជ ា ត ិ ។',
                'category' => 'events-and-seminars',
                'is_featured' => false,
                'published_at' => now()->subDays(63),
            ],
            [
                'title_en' => 'Judicial Clerkship Opportunities Available',
                'title_km' => ' ឱ ក ា ស ក ា រ ណ ា ត ន ិ ច ប ា ប ន ុ ង ស ា ន ុ រ ដ ោ ល',
                'content_en' => 'NUM International Program of Legal Studies is pleased to announce new judicial clerkship opportunities with the Court of Appeal. Selected students will work closely with judges and gain valuable experience in judicial decision-making.',
                'content_km' => ' ក ម វ ិ ធ ី អ ន ម ្ ត រ ជ ា ត ិ NUM ម ា ន ក ា រ រ ី ក រ ា យ ឱ ក ា ស ក ា រ ណ ា ត ន ិ ច ប ា ប ន ុ ង ស ា ន ុ រ ដ ោ ល ។',
                'excerpt_en' => 'New judicial clerkship opportunities with the Court of Appeal.',
                'excerpt_km' => ' ឱ ក ា ស ក ា រ ណ ា ត ន ិ ច ប ា ប ន ុ ង ស ា ន ុ រ ដ ោ ល ថ ធ ម ី ថ ន ម ួ យ ។',
                'category' => 'academic-programs',
                'is_featured' => false,
                'published_at' => now()->subDays(65),
            ],
            [
                'title_en' => 'Cyber Law and Digital Rights Conference',
                'title_km' => ' ស ន ្ ន ិ ស ី ទ ច ប ា ប ់ ច ប ា ប ឌ ី ជ ី ថ ល ន ិ ង ស ិ ទ ្ ធ ិ ឌ ី ជ ី ថ ល',
                'content_en' => 'Join us for a conference on Cyber Law and Digital Rights, exploring the legal challenges of the digital age. Topics include data protection, online speech regulation, and digital commerce.',
                'content_km' => ' ច ូ ល រ ួ ម ជ ា ម ួ យ យ ើ ង ស ម ្ រ ា ប ន ស ន ្ ន ិ ស ី ទ ច ប ា ប ់ ច ប ា ប ឌ ី ជ ី ថ ល ។',
                'excerpt_en' => 'Conference on Cyber Law and Digital Rights exploring legal challenges of the digital age.',
                'excerpt_km' => ' ស ន ្ ន ិ ស ី ទ ច ប ា ប ់ ច ប ា ប ឌ ី ជ ី ថ ល ន ិ ង ស ិ ទ ្ ធ ិ ឌ ី ជ ី ថ ល ។',
                'category' => 'events-and-seminars',
                'is_featured' => false,
                'published_at' => now()->subDays(68),
            ],
            [
                'title_en' => 'Corporate Law Summer Internship Program',
                'title_km' => ' ក ម វ ិ ធ ី ក ម ស ិ ក រ ត ុ ណ ី យ ច ប ា ប ស ា ង រ ា ជ យ ច ប ា ប',
                'content_en' => 'NUM International Program of Legal Studies announces a new summer internship program with leading corporate law firms in Cambodia. Students will gain practical experience in corporate transactions and commercial law.',
                'content_km' => ' ក ម វ ិ ធ ី អ ន ្ ត រ ជ ា ត ិ NUM ប ធ ក ា ស ព ី ក ម វ ិ ធ ី ក ម ស ិ ក រ ត ុ ណ ី យ ថ ធ ម ី ថ ន ម ួ យ ។',
                'excerpt_en' => 'New summer internship program with leading corporate law firms in Cambodia.',
                'excerpt_km' => ' ក ម វ ិ ធ ី ក ម ស ិ ក រ ត ុ ណ ី យ ស ា ង រ ា ជ យ ច ប ា ប ។',
                'category' => 'academic-programs',
                'is_featured' => false,
                'published_at' => now()->subDays(70),
            ],
            [
                'title_en' => 'International Law Reading Group Launched',
                'title_km' => ' ប ង ្ ក ា រ ក ម វ ិ ធ ី អ ន ុ រ ូ ស ស ា ន ុ ច ប ា ប ច ប ា ប អ ន ្ ត រ ជ ា ត ិ',
                'content_en' => 'NUM International Program of Legal Studies is launching a new International Law Reading Group. Students will meet weekly to discuss classic and contemporary works in international law.',
                'content_km' => ' ក ម វ ិ ធ ី អ ន ្ ត រ ជ ា ត ិ NUM ក ត ព ុ ង រ ប ង ្ ក ា រ ក ម វ ិ ធ ី អ ន ុ រ ូ ស ស ា ន ុ ច ប ា ប ច ប ា ប អ ន ្ ត រ ជ ា ត ិ ។',
                'excerpt_en' => 'New International Law Reading Group for weekly discussions on international law.',
                'excerpt_km' => ' ក ម វ ិ ធ ី អ ន ុ រ ូ ស ស ា ន ុ ច ប ា ប ច ប ា ប អ ន ្ ត រ ជ ា ត ិ ។',
                'category' => 'student-life',
                'is_featured' => false,
                'published_at' => now()->subDays(72),
            ],
            [
                'title_en' => 'Legal Technology and Innovation Forum',
                'title_km' => ' វ ិ ធ ី ន ិ ច ស រ វ ជ ស ច ប ា ប ន ិ ង ន ា ណ ូ ត ស ា ន ុ',
                'content_en' => 'NUM International Program of Legal Studies is hosting a forum on Legal Technology and Innovation. Learn about artificial intelligence in law, legal tech startups, and the future of legal practice.',
                'content_km' => ' ក ម វ ិ ធ ី អ ន ្ ត រ ជ ា ត ិ NUM ក ត ព ុ ង រ រ ួ ម ម ុ ខ វ ិ ធ ី ន ិ ច ស រ វ ជ ស ។',
                'excerpt_en' => 'Forum on Legal Technology and Innovation exploring AI in law and future of legal practice.',
                'excerpt_km' => ' វ ិ ធ ី ន ិ ច ស រ វ ជ ស ច ប ា ប ន ិ ង ន ា ណ ូ ត ។',
                'category' => 'events-and-seminars',
                'is_featured' => false,
                'published_at' => now()->subDays(75),
            ],
            [
                'title_en' => 'Public Interest Law Clinic Expands Services',
                'title_km' => ' គ េ ហ ទ ព ថ រ ច ប ា ប ស ា ហ គ ម ន ៍ ស ា ធ ុ ា ខ ណ ៈ ព ឹ ត ដ ល ស ា ប យ ត ល',
                'content_en' => 'The Public Interest Law Clinic at NUM International Program of Legal Studies is expanding its services to include more community legal education and advocacy programs.',
                'content_km' => ' គ េ ហ ទ ព ថ រ ច ប ា ប ស ា ហ គ ម ន ៍ ស ា ធ ុ ា ខ ណ ៈ ន ិ ស ា ហ គ ម ន ៍ ន ន ប ្ រ ួ ម រ ប ស យ ើ ត ប ា ន ក � រ ទ រ ម ា រ ខ គ ត ់ ក ា រ អ ប ា ប ច ប ា ប ។',
                'excerpt_en' => 'Public Interest Law Clinic expands services for community legal education.',
                'excerpt_km' => ' គ េ ហ ទ ព ថ រ ច ប ា ប ស ា ហ គ ម ន ៍ ស ា ធ ុ ា ខ ណ ៈ ព ង ្ យ ស ា ប យ ត ល ។',
                'category' => 'student-life',
                'is_featured' => false,
                'published_at' => now()->subDays(78),
            ],
            [
                'title_en' => 'Migration and Refugee Law Seminar',
                'title_km' => ' ស ិ ក ្ ខ ា ស ា ល ា ច ប ា ប ់ ម ិ ន ា រ ស ន ិ ង ច ប ា ប ន ិ ង ហ ួ ណ ុ ង',
                'content_en' => 'Join us for a seminar on Migration and Refugee Law, examining international frameworks for refugee protection and challenges facing migrants in Southeast Asia.',
                'content_km' => ' ច ូ ល រ ួ ម ជ ា ម ួ យ យ ើ ង ស ម ្ រ ា ប ន ស ិ ក ្ ខ ា ស ា ល ា ច ប ា ប ់ ម ិ ន ា រ ស ។',
                'excerpt_en' => 'Seminar on Migration and Refugee Law examining international refugee protection frameworks.',
                'excerpt_km' => ' ស ិ ក ្ ខ ា ស ា ល ា ច ប ា ប ់ ម ិ ន ា រ ស ន ិ ង ច ប ា ប ។',
                'category' => 'events-and-seminars',
                'is_featured' => false,
                'published_at' => now()->subDays(80),
            ],
            [
                'title_en' => 'Third-Year Students Complete Intensive Moot Court Training',
                'title_km' => ' ន ិ ស ធ ស ត ឆ ល ខ ត រ ស ា ប យ ល ខ ត រ ស ា ប យ ត ល ប ញ ច ប ា ប ត ុ ល ា ក ា រ ម ិ ន ព ិ ត',
                'content_en' => 'Third-year students at NUM International Program of Legal Studies have completed an intensive moot court training program. The training prepared them for national and international moot court competitions.',
                'content_km' => ' ន ិ ស ធ ស ត ឆ ល ខ ត រ ស ា ប យ ន ិ ស ធ ស ត ក ម វ ិ ធ ី អ ន ្ ត រ ជ ា ត ិ NUM ប ា ន ប ញ ច ប ា ប ក ម វ ិ ធ ី ប ញ ច ប ា ប ត ុ ល ា ក ា រ ម ិ ន ព ិ ត ។',
                'excerpt_en' => 'Third-year students complete intensive moot court training for competitions.',
                'excerpt_km' => ' ន ិ ស ធ ស ត ឆ ល ខ ត រ ស ា ប យ ប ញ ច ប ា ប ត ុ ល ា ក ា រ ម ិ ន ព ិ ត ។',
                'category' => 'student-life',
                'is_featured' => false,
                'published_at' => now()->subDays(82),
            ],
            [
                'title_en' => 'Intellectual Property Law Workshop',
                'title_km' => ' ស ិ ក ្ ខ ា ស ា ល ា ច ប ា ប ់ ទ ្ យ ា ស ា ន ុ ប រ ិ ច ប ា ប',
                'content_en' => 'NUM International Program of Legal Studies is hosting a workshop on Intellectual Property Law. Topics include trademark registration, copyright protection, and patent law in Cambodia.',
                'content_km' => ' ក ម វ ិ ធ ី អ ន ្ ត រ ជ ា ត ិ NUM ក ត ព ុ ង រ រ ួ ម ម ុ ខ ស ិ ក ្ ខ ា ស ា ល ា ច ប ា ប ់ ទ ្ យ ា ស ា ន ុ ប រ ិ ច ។',
                'excerpt_en' => 'Workshop on Intellectual Property Law covering trademarks, copyrights, and patents.',
                'excerpt_km' => ' ស ិ ក ្ ខ ា ស ា ល ា ច ប ា ប ់ ទ ្ យ ា ស ា ន ុ ប រ ិ ច ។',
                'category' => 'events-and-seminars',
                'is_featured' => false,
                'published_at' => now()->subDays(85),
            ],
            [
                'title_en' => 'Law and Development Research Grant Awarded',
                'title_km' => ' ក ា រ ផ ល ើ ម ួ យ ស រ វ ជ ំ រ ា វ ច ប ា ប ់ ច ប ា ប ន ិ ង អ ភ ិ ប រ ក ភ ា ព',
                'content_en' => 'A research team from NUM International Program of Legal Studies has been awarded a major grant to study the relationship between law and economic development in Cambodia.',
                'content_km' => ' ក ា រ ផ ល ើ ម ួ យ ស រ វ ជ ំ រ ា វ ពី ក ម វ ិ ធ ី អ ន ្ ត រ ជ ា ត ិ NUM ប ា ន ប ា ន ប ើ ក ក ា រ ផ ល ើ ម ួ យ ដ ើ ន ស ិ ក ្ ស រ វ ជ ំ រ ា វ ទ ស ន ន ម ួ យ ច ប ា ប ់ ច ប ា ប ន ិ ង អ ភ ិ ប រ ក ភ ា ព ។',
                'excerpt_en' => 'Research grant awarded to study law and economic development in Cambodia.',
                'excerpt_km' => ' ក ា រ ផ ល ើ ម ួ យ ស រ វ ជ ំ រ ា វ ច ប ា ប ់ ច ប ា ប ន ិ ង អ ភ ិ ប រ ក ភ ា ព ។',
                'category' => 'research-and-publications',
                'is_featured' => false,
                'published_at' => now()->subDays(88),
            ],
            [
                'title_en' => 'Bankruptcy and Insolvency Law Training',
                'title_km' => ' ក ា រ ហ ា ប ឋ ា រ ច ប ា ប ន ិ ង ស ភ ា រ ស ន ិ ង អ ំ ណ ា ត ន ិ ង',
                'content_en' => 'NUM International Program of Legal Studies is offering a training program on Bankruptcy and Insolvency Law. This program is essential for students interested in corporate law and financial restructuring.',
                'content_km' => ' ក ម វ ិ ធ ី អ ន ្ ត រ ជ ា ត ិ NUM ក ត ព ុ ង រ ផ ល ើ ក ម វ ិ ធ ី ប ហ ា ប ឋ ា រ ច ប ា ប ន ិ ង ស ភ ា រ ស ។',
                'excerpt_en' => 'Training program on Bankruptcy and Insolvency Law for corporate law students.',
                'excerpt_km' => ' ក ម វ ិ ធ ី ប ហ ា ប ឋ ា រ ច ប ា ប ន ិ ង ស ភ ា រ ស ។',
                'category' => 'academic-programs',
                'is_featured' => false,
                'published_at' => now()->subDays(90),
            ],
            [
                'title_en' => 'Pro Bono Week Promotes Legal Service',
                'title_km' => ' ស ប ធ ម ៌ ប ូ ត ស ា ន ុ ច ប ា ប ស ា ហ គ ម ន ៍ ច ប ា ប ប រ ែ ស',
                'content_en' => 'NUM International Program of Legal Studies celebrates Pro Bono Week, promoting volunteer legal services to underserved communities. Students will participate in various outreach activities.',
                'content_km' => ' ក ម វ ិ ធ ី អ ន ្ ត រ ជ ា ត ិ NUM អ ន ុ ញ ច ា រ ស ប ធ ម ៌ ប ូ ត ស ា ន ុ ច ប ា ប ។',
                'excerpt_en' => 'Pro Bono Week promotes volunteer legal services to underserved communities.',
                'excerpt_km' => ' ស ប ធ ម ៌ ប ូ ត ស ា ន ុ ច ប ា ប ស ា ហ គ ម ន ៍ ។',
                'category' => 'student-life',
                'is_featured' => false,
                'published_at' => now()->subDays(92),
            ],
            [
                'title_en' => 'International Commercial Law Course Launched',
                'title_km' => ' ប ង ្ ក ា រ វ គ ច ក ា រ ច ប ា ប ព ា ណ ិ ជ ក ម ្ ម អ ន ្ ត រ ជ ា ត ិ',
                'content_en' => 'NUM International Program of Legal Studies has launched a new course in International Commercial Law. The course covers international sales, shipping law, and commercial arbitration.',
                'content_km' => ' ក ម វ ិ ធ ី អ ន ្ ត រ ជ ា ត ិ NUM ប ា ន ប ើ ក វ គ ច ក ា រ ថ ធ ម ី ថ ន ម ួ យ ច ប ា ប ព ា ណ ិ ជ ក ម ្ ម អ ន ្ ត រ ជ ា ត ិ ។',
                'excerpt_en' => 'New course in International Commercial Law covering sales, shipping, and arbitration.',
                'excerpt_km' => ' វ គ ច ក ា រ ច ប ា ប ព ា ណ ិ ជ ក ម ្ ម អ ន ្ ត រ ជ ា ត ិ ។',
                'category' => 'academic-programs',
                'is_featured' => false,
                'published_at' => now()->subDays(95),
            ],
            [
                'title_en' => 'Alumni Network Event Connects Graduates',
                'title_km' => ' ព ិ ធ ី ក ា រ ង ្ ហ ា ត រ ប ណ ា ត ន ិ ច អ ត ន ត ា ល ង ក ធ ុ ច ល ុ យ',
                'content_en' => 'NUM International Program of Legal Studies hosted its annual Alumni Network Event, bringing together graduates from all graduating classes to network and share career experiences.',
                'content_km' => ' ក ម វ ិ ធ ី អ ន ្ ត រ ជ ា ត ិ NUM ប ា ន ប ើ ក ព ិ ធ ី ក ា រ ង ្ ហ ា ត រ អ ត ន ត ា ល ង ក ។',
                'excerpt_en' => 'Annual Alumni Network Event brings together graduates to share career experiences.',
                'excerpt_km' => ' ព ិ ធ ី ក ា រ ង ្ ហ ា ត រ អ ត ន ត ា ល ង ក ។',
                'category' => 'news-and-announcements',
                'is_featured' => false,
                'published_at' => now()->subDays(98),
            ],
            [
                'title_en' => 'Tax Law Certification Program',
                'title_km' => ' ក ម វ ិ ធ ី វ ិ ធ យ ស ា ន ុ ច ប ា ប ច ប ា ប រ ដ ប',
                'content_en' => 'NUM International Program of Legal Studies is offering a new Tax Law Certification Program. This program provides comprehensive training in Cambodian tax law and international taxation.',
                'content_km' => ' ក ម វ ិ ធ ី អ ន ្ ត រ ជ ា ត ិ NUM ក ត ព ុ ង រ ផ ល ើ ក ម វ ិ ធ ី វ ិ ធ យ ស ា ន ុ ច ប ា ប ច ប ា ប រ ដ ប ។',
                'excerpt_en' => 'New Tax Law Certification Program for comprehensive training in tax law.',
                'excerpt_km' => ' ក ម វ ិ ធ ី វ ិ ធ យ ស ា ន ុ ច ប ា ប ច ប ា ប រ ដ ប ។',
                'category' => 'academic-programs',
                'is_featured' => false,
                'published_at' => now()->subDays(100),
            ],
            [
                'title_en' => 'International Law Society Hosts Annual Gala',
                'title_km' => ' ស ម ា គ ម ច ប ា ប អ ន ្ ត រ ជ ា ត ិ រ ួ ម ម ុ ខ ព ិ ធ ី ក ា រ ផ ា ន ិ ច ប ា ប ប រ ិ ច',
                'content_en' => 'The International Law Society at NUM International Program of Legal Studies hosted its annual gala, celebrating student achievements and recognizing outstanding contributions to the program.',
                'content_km' => ' ស ម ា គ ម ច ប ា ប អ ន ្ ត រ ជ ា ត ិ ន ិ ស ា ហ គ ម ន ៍ ន ន ប ្ រ ួ ម រ ប ស យ ើ ត ប ា ន ប ើ ក ព ិ ធ ី ក ា រ ផ ា ន ិ ច ប ា ប ។',
                'excerpt_en' => 'International Law Society hosts annual gala celebrating student achievements.',
                'excerpt_km' => ' ព ិ ធ ី ក ា រ ផ ា ន ិ ច ប ា ប ប រ ិ ច ស ម ា គ ម ច ប ា ប អ ន ្ ត រ ជ ា ត ិ ។',
                'category' => 'student-life',
                'is_featured' => false,
                'published_at' => now()->subDays(102),
            ],
            [
                'title_en' => 'Labor Law Reform Symposium',
                'title_km' => ' ស ន ្ ន ិ ស ី ទ ច ប ា ប ់ កំ ណ ែ ទ ម្ រ ង់ ច ប ា ប ់ ក ម ្ ម ប ្ រ ម ័ យ',
                'content_en' => 'NUM International Program of Legal Studies is hosting a symposium on Labor Law Reform in Cambodia. Experts will discuss current challenges and proposed reforms to labor legislation.',
                'content_km' => ' ក ម វ ិ ធ ី អ ន ្ ត រ ជ ា ត ិ NUM ក ត ព ុ ង រ រ ួ ម ម ុ ខ ស ន ្ ន ិ ស ី ទ ច ប ា ប ់ កំ ណ ែ ទ ម្ រ ង់ ច ប ា ប ់ ក ម ្ ម ប ្ រ ម ័ យ ។',
                'excerpt_en' => 'Symposium on Labor Law Reform discussing challenges and proposed reforms.',
                'excerpt_km' => ' ស ន ្ ន ិ ស ី ទ ច ប ា ប ់ កំ ណ ែ ទ ម្ រ ង់ ច ប ា ប ។',
                'category' => 'events-and-seminars',
                'is_featured' => false,
                'published_at' => now()->subDays(105),
            ],
            [
                'title_en' => 'Student Wins National Law Essay Competition',
                'title_km' => ' ន ិ ស ធ ស ត ឈ ន ល ទ ្ យ ក ា រ ស រ សេ រ អ ត ស ថ ា ន ី ច ប ា ប ស ា ង រ � ជ',
                'content_en' => 'A student from NUM International Program of Legal Studies has won first place in the National Law Essay Competition. The essay examined the role of constitutional courts in democratic governance.',
                'content_km' => ' ន ិ ស ធ ស ត ម្ ន ា ក ់ ព ី ក ម វ ិ ធ ី អ ន ្ ត រ ជ ា ត ិ NUM ប ា ន ប ឈ ន ល ទ ្ យ ក ា រ ស រ សេ រ អ ត ស ថ ា ន ី ច ប ា ប ស ា ង រ � ជ ។',
                'excerpt_en' => 'Student wins National Law Essay Competition with essay on constitutional courts.',
                'excerpt_km' => ' ន ិ ស ធ ស ត ឈ ន ល ទ ្ យ ក ា រ ស រ សេ រ អ ត ស ថ ា ន ី ។',
                'category' => 'student-life',
                'is_featured' => true,
                'published_at' => now()->subDays(108),
            ],
            [
                'title_en' => 'Competition Law Workshop for Business Students',
                'title_km' => ' ស ិ ក ្ ខ ា ស ា ល ា ច ប ា ប ់ ច ប ា ប ន ិ ង ប ្ រ ួ ម',
                'content_en' => 'NUM International Program of Legal Studies is offering a workshop on Competition Law for business students. Topics include antitrust law, market competition, and regulatory frameworks.',
                'content_km' => ' ក ម វ ិ ធ ី អ ន ្ ត រ ជ ា ត ិ NUM ក ត ព ុ ង រ ផ ល ើ ស ិ ក ្ ខ ា ស ា ល ា ច ប ា ប ់ ច ប ា ប ន ិ ង ប ្ រ ួ ម ។',
                'excerpt_en' => 'Workshop on Competition Law covering antitrust and market regulation.',
                'excerpt_km' => ' ស ិ ក ្ ខ ា ស ា ល ា ច ប ា ប ់ ច ប ា ប ន ិ ង ប ្ រ ួ ម ។',
                'category' => 'events-and-seminars',
                'is_featured' => false,
                'published_at' => now()->subDays(110),
            ],
            [
                'title_en' => 'Health Law and Policy Conference',
                'title_km' => ' ស ន ្ ន ិ ស ី ទ ច ប ា ប ់ ច ប ា ប ស ុ ត ណ ូ ម ន ិ ង គ ម ា រ ស',
                'content_en' => 'Join us for a conference on Health Law and Policy, examining legal frameworks for healthcare regulation, patient rights, and medical ethics in Cambodia.',
                'content_km' => ' ច ូ ល រ ួ ម ជ ា ម ួ យ យ ើ ង ស ម ្ រ ា ប ន ស ន ្ ន ិ ស ី ទ ច ប ា ប ់ ច ប ា ប ស ុ ត ណ ូ ម ។',
                'excerpt_en' => 'Conference on Health Law and Policy examining healthcare regulation in Cambodia.',
                'excerpt_km' => ' ស ន ្ ន ិ ស ី ទ ច ប ា ប ់ ច ប ា ប ស ុ ត ណ ូ ម ។',
                'category' => 'events-and-seminars',
                'is_featured' => false,
                'published_at' => now()->subDays(112),
            ],
            [
                'title_en' => 'Second Cohort Graduates with Honors',
                'title_km' => ' ជ ន ភ ា ᖇ ទ ី ក ថ ា ប ួ ង ី រ ប ស យ ើ ត ទ ី ក ថ ា ប ួ ង ី រ ប ស យ ើ ត ជ ា ត ា ព ី រ',
                'content_en' => 'NUM International Program of Legal Studies proudly announces the graduation of its second cohort. Many graduates received honors and awards for academic excellence.',
                'content_km' => ' ក ម វ ិ ធ ី អ ន ្ ត រ ជ ា ត ិ NUM ម ា ន ក ា រ ម ូ ទ ន ភ ា ព ក ន ុ ង ក ា រ ប ណ ា ត ន ិ ច ជ ន ភ ា ᖇ ទ ី ក ថ ា ប ួ ង ី រ ។',
                'excerpt_en' => 'Second cohort graduates from NUM International Program with many receiving honors.',
                'excerpt_km' => ' ជ ន ភ ា ᖇ ទ ី ក ថ ា ប ួ ង ី រ ទ ី ក ថ ា ប ួ ង ី រ ។',
                'category' => 'news-and-announcements',
                'is_featured' => true,
                'published_at' => now()->subDays(115),
            ],
            [
                'title_en' => 'Land Law and Property Rights Seminar',
                'title_km' => ' ស ិ ក ្ ខ ា ស ា ល ា ច ប ា ប ់ ដី ធ ន ់ ន ិ ង ស ិ ទ ្ ធ ិ ទ្ យ ា ស ា ន',
                'content_en' => 'NUM International Program of Legal Studies is hosting a seminar on Land Law and Property Rights. Topics include land registration, property disputes, and sustainable land management.',
                'content_km' => ' ក ម វ ិ ធ ី អ ន ្ ត រ ជ ា ត ិ NUM ក ត ព ុ ង រ រ ួ ម ម ុ ខ ស ិ ក ្ ខ ា ស ា ល ា ច ប ា ប ់ ដី ធ ន ់ ។',
                'excerpt_en' => 'Seminar on Land Law and Property Rights covering registration and disputes.',
                'excerpt_km' => ' ស ិ ក ្ ខ ា ស ា ល ា ច ប ា ប ់ ដី ធ ន ់ ន ិ ង ស ិ ទ ្ ធ ិ ។',
                'category' => 'events-and-seminars',
                'is_featured' => false,
                'published_at' => now()->subDays(118),
            ],
            [
                'title_en' => 'Women in Law Leadership Forum',
                'title_km' => ' វ ិ ធ ី ន ិ ច ស រ វ ជ ស ន ា រ ត ន ិ ច ច ប ា ប ់ ស ា ន ុ រ ដ ṅ',
                'content_en' => 'NUM International Program of Legal Studies is hosting a Women in Law Leadership Forum. The event will feature female legal professionals discussing their career paths and leadership experiences.',
                'content_km' => ' ក ម វ ិ ធ ី អ ន ្ ត រ ជ ា ត ិ NUM ក ត ព ុ ង រ វ ិ ធ ី ន ិ ច ស រ វ ជ ស ន ា រ ត ។',
                'excerpt_en' => 'Women in Law Leadership Forum featuring female legal professionals.',
                'excerpt_km' => ' វ ិ ធ ី ន ិ ច ស រ វ ជ ស ន ា រ ត ។',
                'category' => 'events-and-seminars',
                'is_featured' => false,
                'published_at' => now()->subDays(120),
            ],
            [
                'title_en' => 'Criminal Law Reform Conference',
                'title_km' => ' ស ន ្ ន ិ ស ី ទ ក ំ ណ ែ ទ ម រ ង ច ប ា ប ់ ច ប ា ប ព ិ ច ល ន ី',
                'content_en' => 'Join us for a conference on Criminal Law Reform, examining proposals for modernizing the criminal justice system in Cambodia and aligning with international standards.',
                'content_km' => ' ច ូ ល រ ួ ម ជ ា ម ួ យ យ ើ ង ស ម ្ រ ា ប ន ស ន ្ ន ិ ស ី ទ ក ំ ណ ែ ទ ម រ ង ច ប ា ប ។',
                'excerpt_en' => 'Conference on Criminal Law Reform examining modernization of criminal justice.',
                'excerpt_km' => ' ស ន ្ ន ិ ស ី ទ ក ំ ណ ែ ទ ម រ ង ច ប ា ប ។',
                'category' => 'events-and-seminars',
                'is_featured' => false,
                'published_at' => now()->subDays(122),
            ],
        ];

        foreach ($articles as $articleData) {
            $categorySlug = $articleData['category'];
            $category = $categories[$categorySlug] ?? $categories->first();

            Article::create([
                'title_en' => $articleData['title_en'],
                'title_km' => $articleData['title_km'],
                'slug' => Str::slug($articleData['title_en']),
                'content_en' => $articleData['content_en'],
                'content_km' => $articleData['content_km'],
                'excerpt_en' => $articleData['excerpt_en'],
                'excerpt_km' => $articleData['excerpt_km'],
                'status' => 'published',
                'is_featured' => $articleData['is_featured'] ?? false,
                'author_id' => $author?->id,
                'category_id' => $category?->id,
                'published_at' => $articleData['published_at'],
                'views' => rand(50, 500),
            ]);
        }

        $this->command->info('Successfully seeded 50 articles about NUM International Program of Legal Studies!');
    }
}
