<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Event;
use App\Models\User;
use Illuminate\Support\Str;

class EventSeeder extends Seeder
{
    public function run(): void
    {
        $organizer = User::where('email', 'admin@university.edu')->first() ?? User::first();

        $events = [
            [
                'title_en' => 'International Law Orientation Day',
                'title_km' => 'ថ្ងៃណែនាំច្បាប់អន្តរជាតិ',
                'description_en' => 'Join us for the official orientation day for new students of NUM International Program of Legal Studies.',
                'description_km' => 'ចូលរួមជាមួយយើងនៅថ្ងៃណែនាំផ្លូវការសម្រាប់និស្សិតថ្មីនៃកម្មវិធីអន្តរជាតិNUM ផ្នែកសិក្សាច្បាប់។',
                'type' => 'other',
                'start_datetime' => '2026-02-25 09:00:00',
                'end_datetime' => '2026-02-25 14:00:00',
                'location' => 'Grand Auditorium, NUM Main Campus',
                'is_registration_required' => false,
                'status' => 'upcoming',
            ],
            [
                'title_en' => 'Legal Research Methods Workshop',
                'title_km' => 'សិក្ខាសាលាវិធីស្រាវជ្រាវច្បាប់',
                'description_en' => 'Learn essential legal research methods and skills for academic success in international law studies.',
                'description_km' => 'រៀនវិធីស្រាវជ្រាវច្បាប់ និងជំនាញចាំបាច់សម្រាប់ភាពជោគជ័យនៅក្នុងការសិក្សាច្បាប់អន្9រជាតិ។',
                'type' => 'workshop',
                'start_datetime' => '2026-03-01 09:00:00',
                'end_datetime' => '2026-03-01 16:00:00',
                'location' => 'Room 301, Law Building',
                'is_registration_required' => true,
                'max_participants' => 40,
                'registration_deadline' => '2026-02-28 23:59:00',
                'status' => 'upcoming',
            ],
            [
                'title_en' => 'Guest Lecture: International Trade Law',
                'title_km' => 'មេទ្យារដ្ឋមន្8្រី ៖ ច្បាប់ពាណិជ្ជកម្មអន្9រជាតិ',
                'description_en' => 'Join us for an insightful lecture on international trade law by Professor Sarah Mitchell from WTO.',
                'description_km' => 'ចូលរួមជាមួយយើងសម្រាប់មេទ្យារដ្ឋមន្8្រីស្តីអំពីច្បាប់ពាណិជ្ជកម្មអន្9រជាតិ ដោយបណ្ឌិត Sarah Mitchell ពី WTO ។',
                'type' => 'seminar',
                'start_datetime' => '2026-03-05 14:00:00',
                'end_datetime' => '2026-03-05 16:30:00',
                'location' => 'Lecture Hall A',
                'is_registration_required' => false,
                'status' => 'upcoming',
            ],
            [
                'title_en' => 'Moot Court Competition 2026',
                'title_km' => 'ការប្រកួតតុលាការមិនពិត 2026',
                'description_en' => 'Annual moot court competition where students demonstrate their legal argumentation skills.',
                'description_km' => 'ការប្រកួតតុលាការមិនពិត ប្រចាំឆ្នាំ ដែលនិស្សិតបង្ហាញជំនាញការដេីរប្រាស់ច្បាប់។',
                'type' => 'competition',
                'start_datetime' => '2026-03-15 08:00:00',
                'end_datetime' => '2026-03-17 18:00:00',
                'location' => 'Courtroom A & B',
                'is_registration_required' => true,
                'max_participants' => 60,
                'registration_deadline' => '2026-03-10 23:59:00',
                'status' => 'upcoming',
            ],
            [
                'title_en' => 'Human Rights Law Symposium',
                'title_km' => 'សន្8និសីទច្បាប់សិទ្ធិមនុស្ស',
                'description_en' => 'A comprehensive symposium on human rights law featuring experts from international organizations.',
                'description_km' => 'សន្8និសីទទូលំទូលាយអំពីច្បាប់សិទ្ធិមនុស្ស ដែលមានអ្នកជំនាញពីអង្គការអន្9រជាតិ។',
                'type' => 'conference',
                'start_datetime' => '2026-03-20 09:00:00',
                'end_datetime' => '2026-03-21 17:00:00',
                'location' => 'Grand Auditorium',
                'is_registration_required' => true,
                'max_participants' => 150,
                'registration_deadline' => '2026-03-15 23:59:00',
                'status' => 'upcoming',
            ],
            [
                'title_en' => 'Legal English Certification Exam',
                'title_km' => 'ការប្រឡងវិញ្ញាបនបត្រភាសាអង់គ្លេសផ្នែកច្បាប់',
                'description_en' => 'Official certification exam for Legal English program participants.',
                'description_km' => 'ការប្រឡងផ្លូវការសម្រាប់អ្នកចូលរួមកម្មវិធីភាសាអង់គ្លេសផ្នែកច្បាប់។',
                'type' => 'other',
                'start_datetime' => '2026-03-25 09:00:00',
                'end_datetime' => '2026-03-25 12:00:00',
                'location' => 'Exam Hall',
                'is_registration_required' => true,
                'max_participants' => 50,
                'registration_deadline' => '2026-03-20 23:59:00',
                'status' => 'upcoming',
            ],
            [
                'title_en' => 'International Arbitration Workshop',
                'title_km' => 'សិក្ខាសាលាអភិបាលកិច្�អន្9រជាតិ',
                'description_en' => 'Hands-on workshop on international arbitration procedures and techniques.',
                'description_km' => 'សិក្ខាសាលាជាក់ស្8តែង អំពីនីតិវិធី និងបច្ចេកទេសអភិបាលកិច្�អន្9រជាតិ។',
                'type' => 'workshop',
                'start_datetime' => '2026-04-01 09:00:00',
                'end_datetime' => '2026-04-01 17:00:00',
                'location' => 'Conference Room 1',
                'is_registration_required' => true,
                'max_participants' => 30,
                'registration_deadline' => '2026-03-28 23:59:00',
                'status' => 'upcoming',
            ],
            [
                'title_en' => 'Environmental Law Conference',
                'title_km' => 'សន្8និសីទច្បាប់បរិស្ថាន',
                'description_en' => 'Conference on environmental law and sustainable development in Cambodia.',
                'description_km' => 'សន្8និសីទអំពីច្បាប់បរិស្ថាន និងការអភិវឌ្ឍប្រកបដោយគុណភាពនៅកម្ពុជា។',
                'type' => 'conference',
                'start_datetime' => '2026-04-10 08:00:00',
                'end_datetime' => '2026-04-11 17:00:00',
                'location' => 'Grand Auditorium',
                'is_registration_required' => true,
                'max_participants' => 120,
                'registration_deadline' => '2026-04-05 23:59:00',
                'status' => 'upcoming',
            ],
            [
                'title_en' => 'Career Fair: Law and Justice',
                'title_km' => 'ពិធីការងារ ៖ ច្បាប់ និងយុត្8តិធម៌',
                'description_en' => 'Connect with leading law firms, corporations, and government agencies.',
                'description_km' => 'ភ្ជាប់ជាមួយក្រុមហ៊ុនច្បាប់ សាជាន់ ស្ថាប័ន រដ្ឋ និង ក្រុមហ៊ុន ធំៗ ។',
                'type' => 'other',
                'start_datetime' => '2026-04-20 09:00:00',
                'end_datetime' => '2026-04-20 17:00:00',
                'location' => 'Campus Main Hall',
                'is_registration_required' => false,
                'status' => 'upcoming',
            ],
            [
                'title_en' => 'Comparative Constitutional Law Seminar',
                'title_km' => 'សិក្ខាសាលាច្បាប់រដ្ឋធម្មនុញ្9ាត8កម្មប្រៀបធៀប',
                'description_en' => 'Explore constitutional law systems around the world with leading scholars.',
                'description_km' => 'ស្វែងយល់ពីប្រព័ន្ធច្បាប់រដ្ឋធម្មនុញ្9ាត8កម្មជុំវិញពិភពលោក ជាមួយអ្នកប្រាជ្ញដ8ល្បី។',
                'type' => 'seminar',
                'start_datetime' => '2026-04-25 14:00:00',
                'end_datetime' => '2026-04-25 17:00:00',
                'location' => 'Lecture Hall B',
                'is_registration_required' => false,
                'status' => 'upcoming',
            ],
            [
                'title_en' => 'Summer Law Program Orientation',
                'title_km' => 'ការណែនាំកម្មវិធីច្បាប់រដូវក្8តៅ',
                'description_en' => 'Orientation session for participants of our International Summer Law Program.',
                'description_km' => 'សម្រាប់អ្នកចូលរួមកម្មវិធីច្បាប់រដូវក្8តៅអន្9រជាតិ។',
                'type' => 'other',
                'start_datetime' => '2026-05-01 10:00:00',
                'end_datetime' => '2026-05-01 12:00:00',
                'location' => 'Conference Room 2',
                'is_registration_required' => true,
                'max_participants' => 40,
                'registration_deadline' => '2026-04-28 23:59:00',
                'status' => 'upcoming',
            ],
            [
                'title_en' => 'Legal Writing Competition',
                'title_km' => 'ការប្រកួតសរសេរច្បាប់',
                'description_en' => 'Annual legal writing competition for all law students.',
                'description_km' => 'ការប្រកួតសរសេរច្បាប់ ប្រចាំឆ្នាំ សម្រាប់និស្សិតច្បាប់ទាំងអស់ ។',
                'type' => 'competition',
                'start_datetime' => '2026-05-10 09:00:00',
                'end_datetime' => '2026-05-10 15:00:00',
                'location' => 'Library Study Room',
                'is_registration_required' => true,
                'max_participants' => 50,
                'registration_deadline' => '2026-05-05 23:59:00',
                'status' => 'upcoming',
            ],
            [
                'title_en' => 'Cyber Law and Digital Rights Conference',
                'title_km' => 'សន្8និសីទច្បាប់តេស្8ត និងសិទ្ធិឌីជ8ីថល',
                'description_en' => 'Explore the legal challenges of the digital age including data protection and online rights.',
                'description_km' => 'ស្វែងយល់ពីបញ្ហាប្រឈមផ្នែកច្បាប់នៃយេីងឌីជ8ីថល រួមមាន ការការពារទិន្នន័យ និង សិទ្ធិអនឡាញ ។',
                'type' => 'conference',
                'start_datetime' => '2026-05-15 09:00:00',
                'end_datetime' => '2026-05-16 17:00:00',
                'location' => 'Innovation Hub',
                'is_registration_required' => true,
                'max_participants' => 80,
                'registration_deadline' => '2026-05-10 23:59:00',
                'status' => 'upcoming',
            ],
            [
                'title_en' => 'Judicial Internship Program Launch',
                'title_km' => 'បើកកម្មវិធីកម្មសិក្សានៅតុលាការ',
                'description_en' => 'Launch of our judicial internship program with the Court of Appeal.',
                'description_km' => 'បើកកម្មវិធីកម្មសិក្សាយ៉ាងផ្8លូវការជាមួយតុលាការឧត្8តមភាព ។',
                'type' => 'other',
                'start_datetime' => '2026-05-20 14:00:00',
                'end_datetime' => '2026-05-20 16:00:00',
                'location' => 'Grand Auditorium',
                'is_registration_required' => true,
                'max_participants' => 30,
                'registration_deadline' => '2026-05-15 23:59:00',
                'status' => 'upcoming',
            ],
            [
                'title_en' => 'International Law Society Inaugural Meeting',
                'title_km' => 'កិច្�ប្រជុំបេះបិទសមាគមច្បាប់អន្9រជាតិ',
                'description_en' => 'First meeting of the newly established International Law Society.',
                'description_km' => 'កិច្�ប្រជុំលើកដំបូងរបស់សមាគមច្បាប់អន្9រជាតិ ដែលបានបង្កើតថ្មី ។',
                'type' => 'other',
                'start_datetime' => '2026-05-25 15:00:00',
                'end_datetime' => '2026-05-25 17:00:00',
                'location' => 'Student Center',
                'is_registration_required' => false,
                'status' => 'upcoming',
            ],
            [
                'title_en' => 'Corporate Law Workshop',
                'title_km' => 'សិក្ខាសាលាច្បាប់ក្រុមហ៊ុន',
                'description_en' => 'Workshop on corporate law, mergers and acquisitions, and business regulations.',
                'description_km' => 'សិក្ខាសាលាអំពីច្បាប់ក្រុមហ៊ុន ការរបូត និង ទទួល ក្រុមហ៊ុន និង បទប្8បញ្ញត្8ិ ពាណិជ្ជ កម្ម ។',
                'type' => 'workshop',
                'start_datetime' => '2026-06-01 09:00:00',
                'end_datetime' => '2026-06-01 17:00:00',
                'location' => 'Conference Room 1',
                'is_registration_required' => true,
                'max_participants' => 35,
                'registration_deadline' => '2026-05-28 23:59:00',
                'status' => 'upcoming',
            ],
            [
                'title_en' => 'Intellectual Property Law Seminar',
                'title_km' => 'សិក្ខាសាលាច្បាប់ទ្រព្9សម្8បត្8ិបញ8ញា',
                'description_en' => 'Learn about trademark, copyright, and patent law in Cambodia.',
                'description_km' => 'រៀនអំពី ច្បាប់ និមិត្8 សញ8 ញ ា របស់ បេ ស រ ក ្ រ ័ យ ច ប ា ប ់ ន ិ ង ច ប ា ប ់ ផ ា ន ិ ច ល វេ ប ្ រ ៅ ប ា ប ់ ន ិ ង ន ិ ច ល រ ័ យ ។',
                'type' => 'seminar',
                'start_datetime' => '2026-06-10 13:00:00',
                'end_datetime' => '2026-06-10 16:00:00',
                'location' => 'Lecture Hall A',
                'is_registration_required' => false,
                'status' => 'upcoming',
            ],
            [
                'title_en' => 'Legal Aid Clinic Volunteer Training',
                'title_km' => 'ហ្វឹ ក ហ ៃ ប ស ា យ អ ៅ ប ា ប ស ា ហ គ ម ន ៍ ច ប ា ប ក ម ្ ម ស ិ ក ្ ស ា',
                'description_en' => 'Training session for students participating in our legal aid clinic program.',
                'description_km' => ' ស ិ ក ដ ា ស ា ន ុ រ ស ហ ស ា យ អ ៅ ប ា ប ស ា ហ គ ម ន ៍ ច ប ា ប ន ិ ស ធ ស ត ដ ែ ល ម ា ន ក ម វ ិ ធ ី គ េ ហ ទ ព ថ រ ជ ួ យ ច ប ា ប ។',
                'type' => 'workshop',
                'start_datetime' => '2026-06-15 09:00:00',
                'end_datetime' => '2026-06-15 14:00:00',
                'location' => 'Room 201',
                'is_registration_required' => true,
                'max_participants' => 25,
                'registration_deadline' => '2026-06-12 23:59:00',
                'status' => 'upcoming',
            ],
            [
                'title_en' => 'Migration and Refugee Law Symposium',
                'title_km' => ' ស ន ្ ន ិ ស ី ទ ច ប ា ប ់ ម ិ ន ា រ ស ន ិ ង ច ប ា ប ន ិ ង ហ ួ ណ ុ ង',
                'description_en' => 'Symposium on international migration law and refugee protection mechanisms.',
                'description_km' => ' ស ន ្ ន ិ ស ី ទ អ ំ ព ី ច ប ា ប ់ ម ិ ន ា រ ស អ ន្ ត រ ជ ា ត ិ ន ិ ង យ ន ្ ត ក ា រ ក ា រ ព ា រ ព ី ច ប ា ប ។',
                'type' => 'conference',
                'start_datetime' => '2026-06-20 09:00:00',
                'end_datetime' => '2026-06-21 17:00:00',
                'location' => 'Grand Auditorium',
                'is_registration_required' => true,
                'max_participants' => 100,
                'registration_deadline' => '2026-06-15 23:59:00',
                'status' => 'upcoming',
            ],
            [
                'title_en' => 'Mock Interview Day',
                'title_km' => ' ថ ្ ង ៃ ប ា ប ន ៃ ស ា យ ស ម ្ រ ា ប ន ស ា យ ស ម ្ រ ា ប',
                'description_en' => 'Practice your interview skills with legal professionals and alumni.',
                'description_km' => ' ហ ា ត ់ ជ ំ ន ា ញ ស ា យ ស ម ្ រ ា ប ជ ា ម ួ យ អ ្ ន ក ជ ំ ន ា ញ ច ប ា ប ់ ន ិ ង អ ត ី ត ន ិ ស ធ ស ត ។',
                'type' => 'workshop',
                'start_datetime' => '2026-06-25 10:00:00',
                'end_datetime' => '2026-06-25 16:00:00',
                'location' => 'Career Center',
                'is_registration_required' => true,
                'max_participants' => 40,
                'registration_deadline' => '2026-06-22 23:59:00',
                'status' => 'upcoming',
            ],
            [
                'title_en' => 'Tax Law Certification Program',
                'title_km' => ' ក ម វ ិ ធ ី វ ិ ធ យ ស ា ន ុ ច ប ា ប ច ប ា ប រ ដ ប',
                'description_en' => 'Start of the Tax Law Certification Program with expert practitioners.',
                'description_km' => ' ច ា ប រ ប ស ក ម វ ិ ធ ី វ ិ ធ យ ស ា ន ុ ច ប ា ប ច ប ា ប រ ដ ប ជ ា ម ួ យ អ ្ ន ក ជ ំ ន ា ញ ដ ៏ ប ា យ ដ ៏ ។',
                'type' => 'workshop',
                'start_datetime' => '2026-07-01 09:00:00',
                'end_datetime' => '2026-07-03 17:00:00',
                'location' => 'Conference Room 1',
                'is_registration_required' => true,
                'max_participants' => 30,
                'registration_deadline' => '2026-06-28 23:59:00',
                'status' => 'upcoming',
            ],
            [
                'title_en' => 'International Criminal Law Lecture',
                'title_km' => ' ម េ ទ ្ យ ា រ ដ ្ ឋ ម ន ្ ត ្ រ ៖ ច ប ា ប ់ ព ិ ទ ្ យ អ ន ្ ត រ ជ ា ត ិ',
                'description_en' => 'Guest lecture by ICC prosecutor on international criminal law and justice.',
                'description_km' => ' ម េ ទ ្ យ ា រ ដ ្ ឋ ម ន ្ ត ្ រ ដ ោ ល អ ំ ព ី ច ប ា ប ់ ព ិ ទ ្ យ អ ន ្ ត រ ជ ា ត ិ ន ិ ង យ ុ ត ្ ត ធ ម ៌ ព ី អ ន ្ ត រ ជ ា ត ិ ។',
                'type' => 'seminar',
                'start_datetime' => '2026-07-10 14:00:00',
                'end_datetime' => '2026-07-10 16:30:00',
                'location' => 'Lecture Hall A',
                'is_registration_required' => false,
                'status' => 'upcoming',
            ],
            [
                'title_en' => 'Bankruptcy Law Workshop',
                'title_km' => ' ស ិ ក ដ ា ស ា ន ុ រ ស ច ប ា ប ់ ប ហ ា ប ឋ ា រ ច ប ា ប ់',
                'description_en' => 'Workshop on insolvency and bankruptcy law for corporate practice.',
                'description_km' => ' ស ិ ក ដ ា ស ា ន ុ អ ំ ព ី ច ប ា ប ់ ប ហ ា ប ឋ ា រ ច ប ា ប ់ ស ម ្ រ ា ប ន ក ម ្ ម វ ិ ធ ី ក រ ុ ម ហ ៊ ុ ន ។',
                'type' => 'workshop',
                'start_datetime' => '2026-07-15 09:00:00',
                'end_datetime' => '2026-07-15 17:00:00',
                'location' => 'Conference Room 2',
                'is_registration_required' => true,
                'max_participants' => 30,
                'registration_deadline' => '2026-07-12 23:59:00',
                'status' => 'upcoming',
            ],
            [
                'title_en' => 'Alumni Networking Event',
                'title_km' => ' ព ិ ធ ី ក ា រ ង ្ ហ ា ត រ ប ណ ា ត ន ិ ច អ ត ន ត ា ល ង ក',
                'description_en' => 'Connect with alumni from all cohorts at our networking event.',
                'description_km' => ' ភ ្ ជ ា ប ់ ជ ា ម ួ យ អ ត ី ត ន ិ ស ធ ស ត ព ី ជ ំ ន ា ន ់ ផ ា ន ិ ច ល វេ ប ្ រ ៅ ប ា ប ់ ន ិ ស ធ ស ត ។',
                'type' => 'other',
                'start_datetime' => '2026-07-20 18:00:00',
                'end_datetime' => '2026-07-20 21:00:00',
                'location' => 'Rooftop Garden',
                'is_registration_required' => false,
                'status' => 'upcoming',
            ],
            [
                'title_en' => 'Research Methods Training',
                'title_km' => ' ហ ្ វ ឹ ក ហ ៃ ប ស ា យ វ ិ ធ ី ស រ វ ជ ំ រ ា វ',
                'description_en' => 'Advanced training on legal research methodologies and academic writing.',
                'description_km' => ' ហ ្ វ ឹ ក ហ ៃ ប ស ា យ ក ម ស ា ហ គ ម ៍ ល � វ ិ ធ ី ស រ វ ជ ំ រ ា វ ច ប ា ប ់ ន ិ ង ស រ សេ រ ច ប ា ប ់ វ ិ ទ ្ យ ា ល ័ យ ។',
                'type' => 'workshop',
                'start_datetime' => '2026-08-01 09:00:00',
                'end_datetime' => '2026-08-02 17:00:00',
                'location' => 'Library Training Room',
                'is_registration_required' => true,
                'max_participants' => 25,
                'registration_deadline' => '2026-07-28 23:59:00',
                'status' => 'upcoming',
            ],
            [
                'title_en' => 'Competition Law Seminar',
                'title_km' => ' ស ិ ក ដ ា ស ា ន ុ ច ប ា ប ់ ច ប ា ប ់ ន ិ ង ប ្ រ ួ ម',
                'description_en' => 'Seminar on competition law and anti-trust regulations.',
                'description_km' => ' ស ិ ក ដ ា ស ា ន ុ អ ំ ព ី ច ប ា ប ់ ច ប ា ប ់ ន ិ ង ប ្ រ ួ ម ន ិ ង ប ្ រ ច ា រ ស ា ធ ុ ក ម ្ ម ។',
                'type' => 'seminar',
                'start_datetime' => '2026-08-10 14:00:00',
                'end_datetime' => '2026-08-10 17:00:00',
                'location' => 'Lecture Hall B',
                'is_registration_required' => false,
                'status' => 'upcoming',
            ],
            [
                'title_en' => 'Health Law Conference',
                'title_km' => ' ស ន ្ ន ិ ស ី ទ ច ប ា ប ់ ច ប ា ប ់ ស ុ ត ណ ូ ម',
                'description_en' => 'Conference on healthcare law, patient rights, and medical ethics.',
                'description_km' => ' ស ន ្ ន ិ ស ី ទ អ ំ ព ី ច ប ា ប ់ ស ុ ត ណ ូ ម ស ិ ទ ្ ធ ិ អ ្ ន ក ជ ំ ន ា ញ ន ិ ង ធ ម ប វ ិ ទ ្ យ ។',
                'type' => 'conference',
                'start_datetime' => '2026-08-15 09:00:00',
                'end_datetime' => '2026-08-16 17:00:00',
                'location' => 'Grand Auditorium',
                'is_registration_required' => true,
                'max_participants' => 100,
                'registration_deadline' => '2026-08-10 23:59:00',
                'status' => 'upcoming',
            ],
            [
                'title_en' => 'Pro Bono Week Kickoff',
                'title_km' => ' ប ើ ក ស ប ធ ម ៌ ប ូ ត ស ា ន ុ ច ប ា ប',
                'description_en' => 'Launch of Pro Bono Week with volunteer legal services to communities.',
                'description_km' => ' ប ើ ក ក ា រ ស ប ធ ម ៌ ប ូ ត ស ា ន ុ ច ប ា ប ស ា ហ គ ម ន ៍ ច ប ា ប ស ហ គ ម ន ៍ ។',
                'type' => 'other',
                'start_datetime' => '2026-08-20 08:00:00',
                'end_datetime' => '2026-08-20 12:00:00',
                'location' => 'Community Center',
                'is_registration_required' => true,
                'max_participants' => 50,
                'registration_deadline' => '2026-08-18 23:59:00',
                'status' => 'upcoming',
            ],
            [
                'title_en' => 'International Commercial Law Course',
                'title_km' => ' វ គ ច ក ា រ ច ប ា ប ់ ព ា ណ ិ ជ ក ម ្ ម អ ន ្ ត រ ជ ា ត ិ',
                'description_en' => 'Start of the new International Commercial Law intensive course.',
                'description_km' => ' ច ា ប រ ប ស វ គ ច ក ា រ ច ប ា ប ់ ព ា ណ ិ ជ ក ម ្ ម អ ន ្ ត រ ជ ា ត ិ ថ ធ ម ី ។',
                'type' => 'workshop',
                'start_datetime' => '2026-09-01 09:00:00',
                'end_datetime' => '2026-09-05 17:00:00',
                'location' => 'Conference Room 1',
                'is_registration_required' => true,
                'max_participants' => 30,
                'registration_deadline' => '2026-08-28 23:59:00',
                'status' => 'upcoming',
            ],
            [
                'title_en' => 'Land Law and Property Rights Seminar',
                'title_km' => ' ស ិ ក ដ ា ស ា ន ុ ច ប ា ប ់ ដ ី ធ ន ់ ន ិ ង ស ិ ទ ្ ធ ិ',
                'description_en' => 'Seminar on Cambodian land law and property rights protection.',
                'description_km' => ' ស ិ ក ដ ា ស ា ន ុ អ ំ ព ី ច ប ា ប ់ ដ ី ធ ន ់ ន ិ ង ន ិ ង ស ិ ទ ្ ធ ិ ន ិ ង ក ា រ ក ា រ ព ា រ ក ្ ។',
                'type' => 'seminar',
                'start_datetime' => '2026-09-10 14:00:00',
                'end_datetime' => '2026-09-10 17:00:00',
                'location' => 'Lecture Hall A',
                'is_registration_required' => false,
                'status' => 'upcoming',
            ],
            [
                'title_en' => 'Negotiation Skills Workshop',
                'title_km' => ' ស ិ ក ដ ា ស ា ន ុ ជ ំ ន ា ញ ក ា រ ច រ ច ម ា រ',
                'description_en' => 'Master negotiation techniques with experienced legal practitioners.',
                'description_km' => ' រ ា ប យ ក ប ច រ ច ម ា រ ជ ា ម ួ យ អ ្ ន ក ជ ំ ន ា ញ ច ប ា ប ់ ដ ៏ ប ា យ ដ ៏ ។',
                'type' => 'workshop',
                'start_datetime' => '2026-09-15 09:00:00',
                'end_datetime' => '2026-09-15 16:00:00',
                'location' => 'Conference Room 2',
                'is_registration_required' => true,
                'max_participants' => 25,
                'registration_deadline' => '2026-09-12 23:59:00',
                'status' => 'upcoming',
            ],
            [
                'title_en' => 'Labor Law Reform Symposium',
                'title_km' => ' ស ន ្ ន ិ ស ី ទ ក ម ្ ម រ ង ច ប ា ប ់ ក ម ្ ម ប ្ រ ម ័ យ',
                'description_en' => 'Symposium on labor law reform and workers rights in Cambodia.',
                'description_km' => ' ស ន ្ ន ិ ស ី ទ អ ំ ព ី ក ម ្ ម រ ង ច ប ា ប ់ ក ម ្ ម ប ្ រ ម ័ យ ន ិ ង ស ិ ទ ្ ធ ិ ក ម ្ រ ។',
                'type' => 'conference',
                'start_datetime' => '2026-09-20 09:00:00',
                'end_datetime' => '2026-09-21 17:00:00',
                'location' => 'Grand Auditorium',
                'is_registration_required' => true,
                'max_participants' => 80,
                'registration_deadline' => '2026-09-15 23:59:00',
                'status' => 'upcoming',
            ],
            [
                'title_en' => 'Legal Technology Showcase',
                'title_km' => ' ក ា រ ប ង ្ ហ ា ត រ ប ច ស រ វ ជ ស ច ប ា ប',
                'description_en' => 'Showcase of latest legal tech tools and AI applications in law.',
                'description_km' => ' ក ា រ ប ង ្ ហ ា ត រ ឧ ប ក រ ណ ៍ ប ច ស រ វ ជ ស ច ប ា ប ថ ី ស ម ្ រ ា ប ន ិ ង AI ក ម ្ ម ច ប ា ប ។',
                'type' => 'other',
                'start_datetime' => '2026-09-25 13:00:00',
                'end_datetime' => '2026-09-25 18:00:00',
                'location' => 'Innovation Hub',
                'is_registration_required' => false,
                'status' => 'upcoming',
            ],
            [
                'title_en' => 'Women in Law Leadership Forum',
                'title_km' => ' វ ិ ធ ី ន ិ ច ស រ វ ជ ស ន ា រ ត ន ិ ច ច ប ា ប ់',
                'description_en' => 'Forum celebrating female leaders in the legal profession.',
                'description_km' => ' វ ិ ធ ី ន ិ ច ស រ វ ជ ស ដ េ ី ម ន ា រ ដ ៏ ច ប ា ប ់ ក្ ន ុ ង វ ិ ស ថ យ ច ប ា ប ។',
                'type' => 'seminar',
                'start_datetime' => '2026-10-01 14:00:00',
                'end_datetime' => '2026-10-01 17:00:00',
                'location' => 'Lecture Hall B',
                'is_registration_required' => false,
                'status' => 'upcoming',
            ],
            [
                'title_en' => 'International Law Society Gala Dinner',
                'title_km' => ' ព ិ ធ ី ក ា រ ផ ា ន ិ ច ប ា ប ស ម ា គ ម ច ប ា ប អ ន ្ ត រ ជ ា ត ិ',
                'description_en' => 'Annual gala dinner for International Law Society members.',
                'description_km' => ' ព ិ ធ ី ក ា រ ផ ា ន ិ ច ប ា ប ប រ ិ ច ប ា ប ់ ស ម ា គ ម ច ប ា ប អ ន ្ ត រ ជ ត ិ ។',
                'type' => 'other',
                'start_datetime' => '2026-10-10 18:00:00',
                'end_datetime' => '2026-10-10 22:00:00',
                'location' => 'Grand Ballroom',
                'is_registration_required' => true,
                'max_participants' => 100,
                'registration_deadline' => '2026-10-05 23:59:00',
                'status' => 'upcoming',
            ],
            [
                'title_en' => 'Criminal Law Reform Conference',
                'title_km' => ' ស ន ្ ន ិ ស ី ទ ក ម ្ ម រ ង ច ប ា ប ់ ច ប ា ប ព ិ ច ល ន ី',
                'description_en' => 'Conference on criminal law reform and justice system improvements.',
                'description_km' => ' ស ន ្ ន ិ ស ី ទ អ ំ ព ី ក ម ្ ម រ ង ច ប ា ប ់ ច ប ា ប ព ិ ច ល ន ី ន ិ ង ក ំ ណ ែ ទ ម រ ង យ � ញ ម ។',
                'type' => 'conference',
                'start_datetime' => '2026-10-15 09:00:00',
                'end_datetime' => '2026-10-16 17:00:00',
                'location' => 'Grand Auditorium',
                'is_registration_required' => true,
                'max_participants' => 100,
                'registration_deadline' => '2026-10-10 23:59:00',
                'status' => 'upcoming',
            ],
            [
                'title_en' => 'Research Symposium 2026',
                'title_km' => ' ស ន ្ ន ិ ស ី ទ ស រ វ ជ ំ រ ា វ 2026',
                'description_en' => 'Annual research symposium showcasing faculty and student research.',
                'description_km' => ' ស ន ្ ន ិ ស ី ទ ស រ វ ជ ំ រ ា វ ប ធ រ ច ា រ ស ា ធ ុ ក ម វ ិ ធ ី ប ណ ឌ ិ ត ន ិ ង ន ិ ស ធ ស ត ។',
                'type' => 'conference',
                'start_datetime' => '2026-10-20 09:00:00',
                'end_datetime' => '2026-10-21 17:00:00',
                'location' => 'Main Auditorium',
                'is_registration_required' => false,
                'status' => 'upcoming',
            ],
            [
                'title_en' => 'Constitutional Law Lecture Series',
                'title_km' => ' ក ម រ ត ន ា រ ដ ្ ឋ ធ ម ្ រ ន ុ ញ ធ ា រ ស ា ន ុ ប ្ រ ួ ម',
                'description_en' => 'Comprehensive lecture series on constitutional law and governance.',
                'description_km' => ' ក ម រ ត ន ា រ ដ ្ ឋ ធ ម ្ រ ន ុ ញ ធ ា រ ស ា ន ុ ប ្ រ ួ ម ន ិ ង ក ា ᚠ រ ប ស យ ើ ត ។',
                'type' => 'seminar',
                'start_datetime' => '2026-10-25 10:00:00',
                'end_datetime' => '2026-10-25 13:00:00',
                'location' => 'Lecture Hall A',
                'is_registration_required' => false,
                'status' => 'upcoming',
            ],
            [
                'title_en' => 'WTO and Trade Law Workshop',
                'title_km' => ' ស ិ ក ដ ា ស ា ន ុ WTO ន ិ ង ច ប ា ប ់ ព ា ណ ិ ជ ក ម ្ ម',
                'description_en' => 'Workshop on WTO agreements and international trade regulations.',
                'description_km' => ' ស ិ ក ដ ា ស ា ន ុ អ ំ ព ី ក ិ ច ទ ស ល � រ WTO ន ិ ង ប ្ ប ញ ច ប ា ប ់ ព ា ណ ិ ជ ក ម ្ ម អ ន ្ ត រ ជ ា ត ិ ។',
                'type' => 'workshop',
                'start_datetime' => '2026-11-01 09:00:00',
                'end_datetime' => '2026-11-01 17:00:00',
                'location' => 'Conference Room 1',
                'is_registration_required' => true,
                'max_participants' => 30,
                'registration_deadline' => '2026-10-28 23:59:00',
                'status' => 'upcoming',
            ],
            [
                'title_en' => 'Media Law and Freedom of Speech Seminar',
                'title_km' => ' ស ិ ក ដ ា ស ា ន ុ ច ប ា ប ់ មេ ឌ ា ន ិ ង ស ិ ទ ្ ធ ិ ក ា រ ន ័ យ ច ប ា ប',
                'description_en' => 'Explore media law, freedom of expression, and digital communications.',
                'description_km' => ' ស ិ ក ដ ា ស ា ន ុ អ ំ ព ី ច ប ា ប ់ មេ ឌ ា ន ិ ង ស ិ ទ ្ ធ ិ ក ា រ ន ័ យ ច ប ា ប ន ិ ង ទ ូ រ ស ព ី ឌ ី ថ ល ។',
                'type' => 'seminar',
                'start_datetime' => '2026-11-10 14:00:00',
                'end_datetime' => '2026-11-10 17:00:00',
                'location' => 'Lecture Hall B',
                'is_registration_required' => false,
                'status' => 'upcoming',
            ],
            [
                'title_en' => 'Alumni Career Mentorship Program Launch',
                'title_km' => ' ប ើ ក ក ម វ ិ ធ ី ប ណ ា ត ន ិ ច ម ា រ ស ា ន ុ អ ត ន ត ា ល ង ក',
                'description_en' => 'Launch of mentorship program connecting students with alumni professionals.',
                'description_km' => ' ប ើ ក ក ម វ ិ ធ ី ប ណ ា ត ន ិ ច ម ា រ ស ា ន ុ ភ ្ ជ ា ប ់ ន ិ ស ធ ស ត ជ ា ម ួ យ អ ត ី ត ន ិ ស ធ ស ត វ ិ ជ ំ ន ា ញ ។',
                'type' => 'other',
                'start_datetime' => '2026-11-15 15:00:00',
                'end_datetime' => '2026-11-15 17:00:00',
                'location' => 'Student Center',
                'is_registration_required' => true,
                'max_participants' => 50,
                'registration_deadline' => '2026-11-12 23:59:00',
                'status' => 'upcoming',
            ],
            [
                'title_en' => 'Investment Law Seminar',
                'title_km' => ' ស ិ ក ដ ា ស ា ន ុ ច ប ា ប ់ វ ិ ន ិ ច ប ា ប ់',
                'description_en' => 'Seminar on investment law and investor-state disputes.',
                'description_km' => ' ស ិ ក ដ ា ស ា ន ុ អ ំ ព ី ច ប ា ប ់ វ ិ ន ិ ច ប ា ប ់ ន ិ ង ជ ម រ ប ស យ ើ ត ន ិ ង រ ដ ប ។',
                'type' => 'seminar',
                'start_datetime' => '2026-11-20 09:00:00',
                'end_datetime' => '2026-11-20 12:00:00',
                'location' => 'Lecture Hall A',
                'is_registration_required' => false,
                'status' => 'upcoming',
            ],
            [
                'title_en' => 'Year-End Law Review Conference',
                'title_km' => ' ស ន ្ ន ិ ស ី ទ ស រ វ ជ ំ រ ា វ ច ប ា ប ់ ច ប ា ប ់ ឆ ា ន ន ័ យ',
                'description_en' => 'Annual year-end conference reviewing major legal developments.',
                'description_km' => ' ស ន ្ ន ិ ស ី ទ ប ធ រ ច ា រ ស ា ធ ុ ឆ ា ន ន ័ យ ដ ែ ល ម ា ន ក ា ᚠ រ ប ស យ ើ ត ច ប ា ប ់ ច ប ា ប ។',
                'type' => 'conference',
                'start_datetime' => '2026-12-01 09:00:00',
                'end_datetime' => '2026-12-02 17:00:00',
                'location' => 'Grand Auditorium',
                'is_registration_required' => false,
                'status' => 'upcoming',
            ],
            [
                'title_en' => 'Graduation Ceremony 2026',
                'title_km' => ' ព ិ ធ ី ប ើ ក ប ន ិ ក ា រ ប ួ ង ី រ ប ស យ ើ ត 2026',
                'description_en' => 'Graduation ceremony for the Class of 2026.',
                'description_km' => ' ព ិ ធ ី ប ើ ក ប ន ិ ក ា រ ប ួ ង ី រ ប ស យ ើ ត ថ ្ ង ៃ ប ា ប ់ 2026 ។',
                'type' => 'other',
                'start_datetime' => '2026-12-15 08:00:00',
                'end_datetime' => '2026-12-15 14:00:00',
                'location' => 'Grand Stadium',
                'is_registration_required' => false,
                'status' => 'upcoming',
            ],
            [
                'title_en' => 'NUM IPLaw First Anniversary Celebration',
                'title_km' => ' ប ញ ច ប ា ប ន ិ យ ប ត រ ប ស យ ើ ត ម ុ ខ ដ េ ី ម NUM IPLaw',
                'description_en' => 'Celebrating the first anniversary of NUM International Program of Legal Studies.',
                'description_km' => ' ប ញ ច ប ា ប ន ិ យ ប ត រ ប ស យ ើ ត ម ុ ខ ដ េ ី ម ន ិ ស ធ ស ត ក ម វ ិ ធ ី អ ន ្ ត រ ជ ា ត ិ NUM ។',
                'type' => 'other',
                'start_datetime' => '2026-12-20 17:00:00',
                'end_datetime' => '2026-12-20 21:00:00',
                'location' => 'Grand Ballroom',
                'is_registration_required' => false,
                'status' => 'upcoming',
            ],
            [
                'title_en' => 'Legal Research Methods - Completed',
                'title_km' => ' វ ិ ធ ី ស រ វ ជ ំ រ ា វ ច ប ា ប ់ - ប ា ន ប ើ ក',
                'description_en' => 'Workshop on legal research methods completed successfully.',
                'description_km' => ' ស ិ ក ដ ា ស ា ន ុ វ ិ ធ ី ស រ វ ជ ំ រ ា វ ច ប ា ប ់ ប ា ន ប ើ ក ដ ោ យ ជ ោ គ ជ ័ យ ។',
                'type' => 'workshop',
                'start_datetime' => '2025-12-10 09:00:00',
                'end_datetime' => '2025-12-10 17:00:00',
                'location' => 'Room 301',
                'is_registration_required' => true,
                'max_participants' => 30,
                'status' => 'completed',
            ],
            [
                'title_en' => 'International Law Orientation - Completed',
                'title_km' => ' ក ា រ ណ ែ ន ា ច ប ា ប ច ប ា ប ់ អ ន ្ ត រ ជ ា ត ិ - ប ា ន ប ើ ក',
                'description_en' => 'International law orientation program completed.',
                'description_km' => ' ក ា រ ណ ែ ន ា ច ប ា ប ច ប ា ប ់ អ ន ្ ត រ ជ ា ត ប ិ ា ន ប ើ ក ។',
                'type' => 'other',
                'start_datetime' => '2025-11-15 10:00:00',
                'end_datetime' => '2025-11-15 14:00:00',
                'location' => 'Grand Auditorium',
                'is_registration_required' => false,
                'status' => 'completed',
            ],
        ];

        foreach ($events as $eventData) {
            Event::create([
                'title_en' => $eventData['title_en'],
                'title_km' => $eventData['title_km'],
                'slug' => Str::slug($eventData['title_en']),
                'description_en' => $eventData['description_en'],
                'description_km' => $eventData['description_km'],
                'type' => $eventData['type'],
                'start_datetime' => $eventData['start_datetime'],
                'end_datetime' => $eventData['end_datetime'],
                'location' => $eventData['location'],
                'is_registration_required' => $eventData['is_registration_required'],
                'max_participants' => $eventData['max_participants'] ?? null,
                'registration_deadline' => $eventData['registration_deadline'] ?? null,
                'organizer_id' => $organizer?->id,
                'status' => $eventData['status'],
                'is_active' => true,
            ]);
        }

        $this->command->info('Successfully seeded 50 events about NUM International Program of Legal Studies!');
    }
}
